### ISSUE TITLE
Nodate String and German Localisation

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#10]
In `ngerman-apa.lbx` the bibstring for `nodate` is not defined; keeping in line with `biblatex`'s `german.lbx` one would probably want (I added a missing space)

    nodate           = {{ohne\space Datum}{{}o\adddot\addabbrvspace D\adddot}},

(this translates to "without/no date") or even ("no year")

    nodate           = {{ohne\space Jahr}{{}o\adddot\addabbrvspace J\adddot}},

Using this together with `ngerman-apa.lbx` though, one will find that in the bibliography the D in "o. D." is converted to lowercase.
This seems to be rooted in `\mkbibdateapalongmdy` and friends using `\biblcstring` when calling bibstrings, changing it to `\bibstring` indeed solves the problem.

One might add though that this alone would cause the "O" to be capitalised in the parentheses as well (which is undesirable as far as I can see) if there was not an empty group before it in the bibstring. One could probably also get rid of this problem by injecting a `\midsentence` somewhere.

**Comment by plk** [comment]
Hmm, the APA style should pick up `nodate` from the biblatex definition and therefore shouldn't need its own string?

**Comment by moewew** [comment]
Oh, yes your are absolutely right, I got confused by my MWE. Scrap that. I would argue though that the missing space makes the result not very pleasing to the eye, but that is something I would have to take up with the biblatex bugracker, not here.

The main point of the problem remains though: Since `nodate` is digested by `\mkbibdateapalongmdy` and friends it is wrongly (for German, at least) forced into all lowercase. 

In this MWE (I should have added one right from the start, sorry for that)

    \documentclass[ngerman]{article}
    \usepackage[T1]{fontenc}
    \usepackage[utf8]{inputenc}
    \usepackage{babel}
    \usepackage{csquotes}
    \usepackage[style=apa]{biblatex} 

    \usepackage{filecontents}
    \begin{filecontents*}{\jobname.bib}
    @online{ieee_ieee,
       title = {{IEEE} 802},
       url = {http://www.ieee802.org/},
       author = {{IEEE}},
       urldate = {2015-05-17}
    }
    \end{filecontents*}

    \DeclareLanguageMapping{ngerman}{ngerman-apa} 

    \addbibresource{\jobname.bib}
    \begin{document}
    \cite{ieee_ieee}
    \printbibliography
    \end{document}


you will find that the citation correctly outputs "o. D." with a capital "D", while the bibliography has "o.d." with a lower case "d".

**Comment by plk** [comment]
Ah ok - do you want to submit a patch against the german and ngerman .lbx files?

**Comment by moewew** [comment]
I have never actually done that, if you bear with me though, I'll do my best...

**Comment by plk** [comment]
Just make your fixed file and do, assuming you have the command on your OS (you can always get it, even on Windows):

```
diff -u <original file> <fixed file>
```

Normally you'd redirect this into a file like so:

```
diff -u german.lbx german.lbx.fixed > german.lbx.patch
```
