### ISSUE TITLE
Correct entry type for slide in unpublished student reader?

### ISSUE THREAD

**Issue by DAVBRAE** [plk/biblatex-apa#100]
Dear Peter,
thank you very much for your work for bib latex and apa, which I am trying to use for a master thesis. After considerable time of searching I cannot find a correct entry type for referencing a
slide without author of an unpublished student reader by my professor. 

**This is the given information:**
Slide title: Dimensions of change
Author: not given! (the professor did not reference the content of this specific slide)
Year: not given for the content of this specific slide

Document title: Elective Module Transformation Management and Change
Author/Editor: Martina Eberl
Document: Student Reader
Institution: Berlin Professional School
Year: 2019

The entry type that comes closest to my needs is 10.5:63 (In: http://ftp.fau.de/ctan/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test.pdf)
 - Is that correct?

Unfortunately neither this nor any other I looked through references a specific! content (slide, chapter, etc.) of a presentation or other type of unpublished work or presentation etc., but only the work in general.

What I got trying out the 10.5:63 is: 
Entry type:
INPROCEEDINGS{Eberl2019,
  AUTHOR         = {},
  EDITORA        = {Eberl, Martina},
  EDITORATYPE    = {chair},
  TITLE          = {Dimensions of change},
  MAINTITLE      = {Elective Module: Transformation Management and Change},
  MAINTITLEADDON = {Student Reader / Intake 2018 Berlin Part-time MBA},

Result in Reference list: 
Dimensions of change. (n.d.). In M. Eberl (Chair), _Elective module: transformation man-
agement and change_ [Student reader / intake 2018 berlin part-time mba].

Questions:
- How to get the the Year of the student reader and institution in?
- If no author of the slide content is given, the title of the work should move to the position of the author, correct? 
- Would the document part (Elective module....) be in italics, although not being a stand-alone work? In the adaptation of 10.5:63 above it does put this part in italics and I think it's wrong.

Thank you very much in advance for giving a hand. I am not a programmer nor have a lot of experience so have already spent several hours on figuring out the problem unsuccessfully. 

Best regards, David

**Comment by plk** [comment]
The best forum for questions about formatting is http://tex.stackexchange.com as we frequent there and there is a dedicated `biblatex` question tag. Please post this there and you will be sure to get swift help.
