### ISSUE TITLE
Missing pages field and duplicate editors in @inproceedings

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#106]
Consider
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{moraux,salam}
\printbibliography
\end{document}
```

> Moraux, P. (1979). Le De Anima dans la tradition grècque: Quelques aspects de l’interpretation du traité, de Theophraste à Themistius (G. E. R. Lloyd & G. E. L. Owen, Eds.). In G. E. R. Lloyd & G. E. L. Owen (Eds.), Aristotle on Mind and the Senses [Proceedings of the Seventh Symposium Aristotelicum]
>
> Salam, A. (1968). Weak and electromagnetic interactions (N. Svartholm, Ed.). In N. Svartholm (Ed.), Elementary particle theory: Relativistic groups and analyticity [Proceedings of the Eighth Nobel Symposium], Aspenäsgarden, Lerum.

Note the duplicate editor and the absence of a `pages` field. The only `@inproceedings` in `biblatex-apa-test-references.bib` is

https://github.com/plk/biblatex-apa/blob/07224ffe6705c2b9d1d093ff560e1ea8e3bef382/bibtex/bib/biblatex-apa-test-references.bib#L1501-L1517

which has no `pages` and appears to be the entry for a session rather than a normal conference paper.

I presume the idea for conference papers that were published in a proceedings volume is that once can use `@incollection` instead, but that would have serious backwards compatibility implications for people who build their `.bib` files according to the `biblatex` standard data model.

**Comment by plk** [comment]
Yes, I think this entry shouldn't really be `inproceedings` and `inproceedings` should be fixed as you say. However, I'm not sure what entrytype applies here as `conference` is just a legacy alias to `inproceedings`. I can only really see that `unpublished` applies but this is to much of a catch-all for such structured entries?

**Comment by moewew** [comment]
We added conference data fields to `@unpublished` a while ago in the standard data model (https://github.com/plk/biblatex/issues/687), so this would have been my first thought. But in principle I share your concerns that `@unpublished` feels a bit meh here.

You could define a new type `@conferencetalk`/`@conferencepresentation`/`@conferencesession`/`@conferencecontribution`. It's a pity that `@conference` is taken.

**Comment by plk** [comment]
I have introduced a `PRESENTATION` entrytype and moved all `PROCEEDINGS`/`INPROCEEDINGS` to this is as they made little sense as they were. This frees up `INPROCEEDINGS` to include pages and remove duplicate editors.

**Comment by moewew** [comment]
Sounds like a good plan. I was wondering about the `@proceedings` entries as well: They didn't really fit the description of what `@proceedings` should be.
