### ISSUE TITLE
The keyword = nonacademic test doesn't feel idiomatic

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#116]
Via https://tex.stackexchange.com/q/551658/35864

In order to have the full date printed in `@article` entries one has to give `nonacademic` as keyword. That doesn't quite feel idiomatic to me, keywords are usually only used for bibliography filtering and possibly quick user-defined formatting changes. For a style I'd much prefer `entrysubtype`.

MWE
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[babel=true,german=quotes]{csquotes} 
\usepackage[style=apa,backend=biber,apamaxprtauth=99]{biblatex}

\DeclareFieldFormat{apacase}{#1}

\begin{filecontents*}{\jobname.bib}
@article{SpiegelOnline.2013,
  author      = {Johannes Korge},
  shortauthor = {jok},
  date        = {2013-06-09},
  title       = {Obama verteidigt Abhöraktion Prism},
  url         = {http://www.spiegel.de/politik/deutschland/gespraeche-mit-merkel-obama-verteidigt-in-berlin-abhoeraktion-prism-a-906638.html},
  urldate     = {2016-07-08},
  journal     = {Spiegel Online},
  keywords    = {nonacademic},
}
\end{filecontents*}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{SpiegelOnline.2013}
\printbibliography 
\end{document}
```

**Comment by plk** [comment]
Fixed in DEV - this was a quick hack I think as I didn't have time to look into the dual-use cases of `entrysubtype`.

**Comment by moewew** [comment]
Thanks. That looks much nicer.

Do you think it would be worth it to have backwards compatibility for the `keywords` solution or is this niche enough that `biblatex-apa` can get away with the change?

**Comment by plk** [comment]
This was fairly niche - I'll note in the docs and I don't think it will have much of an impact.
