### ISSUE TITLE
Rendering of @book is broken

### ISSUE THREAD

**Issue by domhardt** [plk/biblatex-apa#120]
Here is the minimal example:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage[babel=true,english=american]{csquotes} 
\usepackage[style = apa, backend = biber, isbn = true, doi = true]{biblatex}

\begin{filecontents*}{lit.bib}
@inbook{Ackermann2017,
	Author = {Ackermann, Laura and Mugge, Ruth and Schoormans, Jan PL},
	Crossref = {PLATE2017},
	Doi = {10.3233/978-1-61499-820-4-1},
	Pages = {1-4},
	Date = {2017},
	Title = {Consumers' attitudes towards product care: an exploratory study of motivators, ability factors and triggers}}

@book{PLATE2017,
	Location = {Amsterdam, The Netherlands},
	Editor = {Bakker, Conny and Mugge, Ruth},
	Isbn = {978-1-61499-820-4},
	Publisher = {IOS Press},
	Title = {{PLATE}: Product Lifetimes And The Environment},
	Date = {2017}}
\end{filecontents*}
\addbibresource{lit.bib}

\begin{document}
\nocite{Ackermann2017}
\printbibliography 
\end{document}
```
Here is the result:
<img width="463" alt="Bildschirmfoto 2020-07-14 um 21 53 20" src="https://user-images.githubusercontent.com/1955290/87470012-7145b880-c61c-11ea-9d56-2c41a059c6cf.png">
And here is the list of the problems:
1. Location of the book is missing.
2. ISBN of the book is missing.

System information:
MacTeX-2020 incl. updates installed by TeX Live Utility
APA BibLATEX style Version 9.13
BibLATEX Version 3.14

**Comment by moewew** [comment]
According to https://apastyle.apa.org/style-grammar-guidelines/references/elements-list-entry

> A location is not required in the source element for most works (e.g., do not include the publisher location for book references).

and the examples in https://apastyle.apa.org/style-grammar-guidelines/references/examples/edited-book-chapter-references don't show a `location` either. 

Can you please point to the relevant rule in the APA 7 manual that requires the location?

---

For the ISBN I can't find any example on the apastyle site showing ISBNs and I couldn't find any guidance that says to include it.

Again can you point to the relevant passage of the manual?

**Comment by domhardt** [comment]
> According to https://apastyle.apa.org/style-grammar-guidelines/references/elements-list-entry
> 
> > A location is not required in the source element for most works (e.g., do not include the publisher location for book references).
> 
> and the examples in https://apastyle.apa.org/style-grammar-guidelines/references/examples/edited-book-chapter-references don't show a `location` either.
> 
> Can you please point to the relevant rule in the APA 7 manual that requires the location?

I'm sorry. By looking at the APA 7 manual and examples I just found out that the location is not necessary any more.

> For the ISBN I can't find any example on the apastyle site showing ISBNs and I couldn't find any guidance that says to include it.
> 
> Again can you point to the relevant passage of the manual?
> 
> Just in case that is the problem: `biblatex-apa` v9.0 and above implement APA style according to the 7th edition of the manual. Previous `biblatex-apa` versions implemented 6th edition style. If you want to continue using 6th edition APA style, you want to load `biblatex-apa6` (`style=apa6,` instead of `style=apa,`).

I have seen the apa6 version among the other BibLaTeX packages but I'm using "style = apa" as in the example provided by me.

As I understand you correctly the option "isbn = true" has no effect when using APA. I can live with that.

Sorry for the inconvenience. There is no problem left. Thank you for pointing me to the correct sources. I'll close my issue with this comment.
