### ISSUE TITLE
biblatex Warning: \DeclareDelimAlias* is deprecated

### ISSUE THREAD

**Issue by bhopmann** [plk/biblatex-apa#125]
Using `biblatex-apa 2020/05/30 v9.13` and `biblatex 2020/08/23 v3.15a (together with Biber 2.15)` I get this warning:

```
Package biblatex Warning: The starred command '\DeclareDelimAlias*' is
(biblatex)                deprecated.
(biblatex)                Use the unstarred version '\DeclareDelimAlias'
(biblatex)                instead
```

**Comment by plk** [comment]
Greetings, I plan to release a new version shortly with this fix in there.

**Comment by h4ppyM** [comment]
Using apa6 version (biblatex-apa6 v8.5 (2020-08-30)) with biblatex v3.15a (2020/08-30) and Biber 2.15 produces the same warning:

> Package biblatex Warning: The starred command '\DeclareDelimAlias*' is
(biblatex) deprecated.
(biblatex) Use the unstarred version '\DeclareDelimAlias'
(biblatex) instead.

**Comment by h4ppyM** [comment]
Using apa6 version (biblatex-apa6 v8.5 (2020-08-30)) with biblatex v3.15a (2020/08-30) and Biber 2.15 produces the same warning:

> Package biblatex Warning: The starred command '\DeclareDelimAlias*' is
(biblatex) deprecated.
(biblatex) Use the unstarred version '\DeclareDelimAlias'
(biblatex) instead.

**Comment by li-ruijie** [comment]
This error seems to have been reintroduced.

**Comment by sourav-majumdar-math** [comment]
In my use adding `\usepackage[english]{babel}` solves the issue.

**Comment by drtoche** [comment]
Just started seeing this. Great package by the way!
