### ISSUE TITLE
Sorting of Same Author with Different Specific Dates (APA 9.47)

### ISSUE THREAD

**Issue by dpharvie** [plk/biblatex-apa#128]
I am referencing two Press Releases from the Oregon Department of Human Services which I have created in my .bib files as:

@report{ORDHS032019,
author = {{Oregon Department of Human Services}},
date = {2019-03-21},
title = {Oregon Department of Human Services Notifies Public of Data Breach},
titleaddon = {Press Release},
url = {https://www.oregon.gov/dhs/DHSNEWS/NewsReleases/Data-Breech-News%20Release-2019-03-21.pdf},
}

@report{ORDHS062019,
author = {{Oregon Department of Human Services}},
date = {2019-06-18},
title = {Notices mailed to 645,000 clients possibly impacted by data breach},
titleaddon = {Press Release},
url = {https://www.oregon.gov/dhs/DHSNEWS/NewsReleases/Notices%20mailed%20to%20645,000%20clients%20possibly%20impacted%20by%20data%20breach.pdf},

The references generated are:

Oregon Department of Human Services. (2019a, June 18). Notices mailed to 645,000 clients possibly impacted by data breach[Press release].https://www.oregon.gov/dhs/DHSNEWS/NewsReleases/Notices%20mailed%20to%20645,000%20clients%20possibly%20impacted%20by%20data%20breach.pdf

Oregon Department of Human Services. (2019b, March 21). Oregon department of human services notifies public of data breach[Press release].https://www.oregon.gov/dhs/DHSNEWS/NewsReleases/Data­Breech­News%20Release­2019­03­21.pdf

From my understanding of APA 9.47, the March press release should be labeled 2019a and the June should be 2019b since these are specific dates.  However, it seems like the sort was on the year only and then the title of the press release.

**Comment by plk** [comment]
Yes, this was a bug - You can get the `apa.bbx` from the commit above and drop it over your current file if you want the tix before the next release. Thanks for reporting this.
