### ISSUE TITLE
Filtering on type=inproceedings produces error

### ISSUE THREAD

**Issue by kleinschmidt** [plk/biblatex-apa#129]
Using `type=inproceedings` in `\printbibliography` should print only those items that are `@inproceedings`, but it prints nothing and there's an error in the log like `Package biblatex Warning: Type 'inproceedings' not found on input line 35.`.  I think this has to do with treating `inproceedings` as an alias for `inbook` because with `type=inbook` it prints BOTH `@inproceedings` and `@inbook` entries.  I suspect there's a similar problem with `book/proceedings` but haven't checked.

Here's MWE

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage[babel=true,english=american]{csquotes} 
\usepackage[style = apa, backend = biber, isbn = true, doi = true]{biblatex}

\begin{filecontents*}{lit.bib}
@inproceedings{blah,
title = {Blah blah blah},
author = {No, Body},
booktitle = {My great converence},
date = {2020},
editor = {Some, body},
publisher = {Really anyone},
location = {Nowhere, USA}
}

@inbook{blah2,
title = {Blah blah blah, blah},
author = {Body, No and Body, Any},
booktitle = {My great converence 2},
date = {2020},
editor = {Some, body},
publisher = {Really anyone},
location = {Nowhere, USA}
}
\end{filecontents*}
\addbibresource{lit.bib}

\begin{document}
\nocite{*}
\printbibliography[title={everything}]

\printbibliography[title={inbook},type=inbook]
\printbibliography[title={inproceedings},type=inproceedings]
\end{document}
```

This prints 

![image](https://user-images.githubusercontent.com/135920/98853930-dd4bf800-2427-11eb-8706-465eb8ca7578.png)

In contrast, when run without `style=apa`, I get

![image](https://user-images.githubusercontent.com/135920/98854008-feace400-2427-11eb-9a81-e647938926c4.png)

Edit: this is with 9.13 (on arch linux, via texlive-biblatexextra 2020.55376-1).

**Comment by plk** [comment]
This is a style issue - `inproceedings` and `inbook` are the same in APA and so any attempt to distinguish them will just not really work - can you use another style if you need to do this?
