### ISSUE TITLE
"Missing number, treated as zero" when command in title field

### ISSUE THREAD

**Issue by johannesbottcher** [plk/biblatex-apa#13]
Following MWE fails with "Missing number, treated as zero." for `\TeX` in the `title` field. The entry is modified from `biblatex-examples.bib`.

```
\documentclass[american]{article}
\usepackage{babel}
\usepackage[style=apa
]{biblatex}
\DeclareLanguageMapping{american}{american-apa}
%\addbibresource{biblatex-examples.bib}
\addbibresource{\jobname.bib}
%\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{knuth:ct:b,
  author       = {Knuth,\TeX Donald E.},
  title        = {\TeX: The Program},
  date         = 1986,
}
\end{filecontents}
\begin{document}
\cite{knuth:ct:b}
\printbibliography
\end{document}
```

The workaround is pretty simple, enclose in an extra pair of braces, or `\protect` the macro. 

There is no problem with `numeric`, it seems to be specific to `apa`. Is that on purpose and the user should take care of correct input? 

PS: the macro in the author field does not throw an error, but the output is quite unexpected :-)

**Comment by plk** [comment]
In general, you will want to protect macros that are not specifically character macros. APA style does do some particular things with title fields and I can perhaps look at this but if protecting/bracing it works for now, that's ok I think. The \TeX in the author field will always cause a mess due to the idiosyncratic bibtex library name parsing routines ...

**Comment by johannesbottcher** [comment]
I happened to stumble upon this and thought i left a note :-)

What do you mean by *idiosyncratic bibtex library name parsing routines ...*? Can you give pointer to relevant docs?

**Comment by plk** [comment]
I mean the library biber uses for .bib parsing (btparse - https://metacpan.org/release/Text-BibTeX) is a little strange in some ways and name parsing is notoriously sensitive.

**Comment by johannesbottcher** [comment]
Thanks for the link; quite a lot to read. 

I think with a statement like *Properly protect macros in the database*, the issue can be closed?
