### ISSUE TITLE
biblatex-apa6 Warning: \DeclareDelimAlias* is deprecated

### ISSUE THREAD

**Issue by h4ppyM** [plk/biblatex-apa#130]
Using apa6 version (biblatex-apa6 v8.5 (2020-08-30)) with biblatex v3.15a (2020/08-30) and Biber 2.15 produces the same warning:

> Package biblatex Warning: The starred command '\DeclareDelimAlias*' is
(biblatex) deprecated.
(biblatex) Use the unstarred version '\DeclareDelimAlias'
(biblatex) instead.

_Originally posted by @h4ppyM in https://github.com/plk/biblatex-apa/issues/125#issuecomment-751475529_

**Comment by h4ppyM** [comment]
Sorry for stupid question: Do I need to do something so the issue will be closed and released?

**Comment by plk** [comment]
No, I will release shortly.
