### ISSUE TITLE
Cite all authors on first citation

### ISSUE THREAD

**Issue by Ntgllr** [plk/biblatex-apa#135]
I'm completely new to LaTeX and wanted to use it writing my seminar paper (I'm a Public Health student in germany)

For citation we need to use either DGP or APA which are very similar. Unfortunately when I first cite an entry from my .bib biblatex wouldn't display every author as required by APA, but starts immediately with using "et al."

`\documentclass[11pt]{article}

    \usepackage[ngerman]{babel}
    \usepackage{filecontents}

    \begin{filecontents}{literature.bib}
    @article{kuepke2020,
      title = {{Gesetz f\"ur den Schutz vor Masern und zur St\"arkung der Impfpr\"avention (Masernschutzgesetz)}},
      author = {K{\"u}pke, NK and {Matysiak-Klose}, D and Siedler, A and Wiechmann, O and Diercke, M},
      year = {2020},
      month = mar,
      publisher = {{Robert Koch-Institut}},
      doi = {10.25646/6526},
      collaborator = {{Koch-Institut}, Robert and {Koch-Institut}, Robert},
      language = {de}
    }
    \end{filecontents}

    \usepackage[backend=biber, style=apa]{biblatex}
    \addbibresource{literature.bib}
    
    
    \begin{document}

    \title{Sample Document}
    \author{Bob Smith}
    \date{Today}
    \maketitle

    Blah blah blah blah blah blah \parencite{kuepke2020}. 

    \printbibliography
    \end{document}`

This Code would output: `Blah blah blah blah blah blah (Küpke et al., 2020).`

Please help me figuring this out.

Regards
Ntgllr

**Comment by moewew** [comment]
This is expected in 7th-edition APA style, cf. https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references. There is no difference between first and subsequent citations any more: APA style goes immediately to "et al."

What you describe sounds like 6th-edition APA style, which you can now get with `biblatex-apa6`'s `style=apa6,`.

```latex
\documentclass[11pt]{article}
\usepackage[ngerman]{babel}
\usepackage{csquotes}
\usepackage[backend=biber, style=apa6]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{kuepke2020,
  title        = {{Gesetz für den Schutz vor Masern und zur Stärkung der Impfprävention (Masernschutzgesetz)}},
  author       = {Küpke, N. K. and Matysiak-Klose, D. and Siedler, A. and Wiechmann, O. and Diercke, M.},
  year         = {2020},
  month        = mar,
  publisher    = {{Robert Koch-Institut}},
  doi          = {10.25646/6526},
  collaborator = {{Koch-Institut}, Robert and {Koch-Institut}, Robert},
  language     = {de},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
Blah blah blah blah blah blah \autocite{kuepke2020}. 

\printbibliography
\end{document}
```

**Comment by Ntgllr** [comment]
> This is expected in 7th-edition APA style, cf. https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references. There is no difference between first and subsequent citations any more: APA style goes immediately to "et al."
> 
> What you describe sounds like 6th-edition APA style, which you can now get with `biblatex-apa6`'s `style=apa6,`.
> 
> ```
> \documentclass[11pt]{article}
> \usepackage[ngerman]{babel}
> \usepackage{csquotes}
> \usepackage[backend=biber, style=apa6]{biblatex}
> 
> \begin{filecontents}{\jobname.bib}
> @article{kuepke2020,
>   title        = {{Gesetz für den Schutz vor Masern und zur Stärkung der Impfprävention (Masernschutzgesetz)}},
>   author       = {Küpke, N. K. and Matysiak-Klose, D. and Siedler, A. and Wiechmann, O. and Diercke, M.},
>   year         = {2020},
>   month        = mar,
>   publisher    = {{Robert Koch-Institut}},
>   doi          = {10.25646/6526},
>   collaborator = {{Koch-Institut}, Robert and {Koch-Institut}, Robert},
>   language     = {de},
> }
> \end{filecontents}
> \addbibresource{\jobname.bib}
> 
> 
> \begin{document}
> Blah blah blah blah blah blah \autocite{kuepke2020}. 
> 
> \printbibliography
> \end{document}
> ```

Thank you so much for your fast reply. This solved the problem for me.
