### ISSUE TITLE
Proposal: Use et al. for APA in spanish instead of "y col." and "y" instead of "&"

### ISSUE THREAD

**Issue by edurojasr** [plk/biblatex-apa#136]
Hi! thanks for the great package

In the Spanish APA package.

May I propose use "et al." instead of "y col." and in the bibliography instead of using "&" use a single "y"

This is because the APA Style 7th Edition in Spanish (Guía Normas APA 7ª edición) Specifies the use of et al. and y, you can verify this here: https://normas-apa.org/wp-content/uploads/Guia-Normas-APA-7ma-edicion.pdf

and here:
https://normas-apa.org/

Others packages uses this parameter

`andothers        = {{et\addabbrvspace al\adddot}{et\addabbrvspace al\adddot}},`

So I think in this case works the same, if people wants to use the "y col." which is not standard they should use 
`\DefineBibliographyStrings` in the main.tex

Thanks for considering this!

**Comment by edurojasr** [comment]
So I've been searching a little bit of how to change the "&" by "y".

this is my complete solution:

First I define

`\DefineBibliographyStrings{spanish}{
    andothers = {et\addabbrvspace al\adddot}, 
    and = {y},
}`
This replace de "y cols." with et al. and change the "and" string with "y"

Then thanks to this answer: https://tex.stackexchange.com/questions/534073/biblatex-change-to-and-in-bibliography

`\DeclareDelimFormat*{finalnamedelim}
  {\ifnum\value{liststop}>2 \finalandcomma\fi\addspace\bibstring{and}\space}

\DeclareDelimFormat[bib]{finalnamedelim}{%
  \ifthenelse{\value{listcount}>\maxprtauth}
    {}
    {\ifthenelse{\value{liststop}>2}
       {\finalandcomma\addspace\bibstring{and}\space}
       {\addspace\bibstring{and}\space}}}

\DeclareDelimFormat[bib]{finalnamedelim:apa:family-given}{%
  \ifthenelse{\value{listcount}>\maxprtauth}
    {}
    {\ifthenelse{\ifcurrentname{groupauthor}\AND%
                 \value{liststop}=2}
     {\addspace\bibstring{and}\space}
     {\finalandcomma\addspace\bibstring{and}\space}}}` 

This chanage all the "&" for "and" so after this "and" gets changed for "y"

I'm using this because "&" its not standard in APA 7th in Spanish in the same way "y cols" aren't

Hope this help!

**Comment by plk** [comment]
So, is there then a consensus on what we should change for the Spanish `.lbx` file as I am planning a new release shortly.

**Comment by edurojasr** [comment]
Hi @plk 

Since both @rmolina and I agree, and the documentation indicates it the change from "y col." to "et. al." is a most to have.

the other change, "&" to "y" as @rmolina says is more complicated, since in Spanish with have this condition of writhing "y" or "e" depending on the fallowing letter and the rules of APA 7 Errata that @rmolina linked changed, I don't have a strong opinion on this. Maybe @rmolina may help us in this.

form me +1 for the "y col." to "et al." change.

**Comment by plk** [comment]
Will be in the next biblatex version.
