### ISSUE TITLE
Missing month and day on @article

### ISSUE THREAD

**Issue by Hen-Rex** [plk/biblatex-apa#142]
Hi

APA 7th ed. requires an article to be shown in the bibliography like this:
https://apastyle.apa.org/style-grammar-guidelines/references/examples/newspaper-article-references

Carey, B. (2019, March 22). Can we get better at forgetting? _The New York Times_. https://www.nytimes.com/2019/03/22/health/memory-forgetting-psychology.html

However, the latest version of biblatex-apa omits the month and date of the newspaper article, like this:

Carey, B. (2019). Can we get better at forgetting? _The New York Times_. https://www.nytimes.com/2019/03/22/health/memory-forgetting-psychology.html

```@article{carey_canwegetbetter_2018,
	location = {New York, {NY}},
	title = {Can we get better at forgetting},
	url = {https://www.nytimes.com/2019/03/22/health/memory-forgetting-psychology.html},
	journaltitle = {The New York Times},
	author = {Carey, B.},
	date = {2018-03-22},
	langid = {english},
}
```

It shows fine if I choose the `@online` / `@misc` type, although it shows [New York Times] in square brackets, and I do not want that.

**Comment by moewew** [comment]
You'll want to specify `entrysubtype = {nonacademic},` for this entry which tells `biblatex-apa` that you are dealing with a non-academic journal that should be cited with full date.

```latex
\documentclass[american]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=apa]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{carey,
  entrysubtype = {nonacademic},
  author       = {Carey, B.},
  title        = {Can we get better at forgetting},
  date         = {2018-03-22},
  journaltitle = {The New York Times},
  location     = {New York, NY},
  url          = {https://www.nytimes.com/2019/03/22/health/memory-forgetting-psychology.html},
  langid       = {english},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,carey}

\printbibliography
\end{document}
```

`biblatex-apa` comes with a comprehensive example `.bib` file, https://github.com/plk/biblatex-apa/blob/master/bibtex/bib/biblatex-apa-test-references.bib, which contains examples for (almost?) all examples in the APA manual. For this question the interesting entries are

https://github.com/plk/biblatex-apa/blob/bf51fec289130300483847b8583d1a09cbed6fce/bibtex/bib/biblatex-apa-test-references.bib#L720-L774

**Comment by Hen-Rex** [comment]
Thanks, I missed that.

Do you know of any way to manually specify that field in Zotero?

**Comment by moewew** [comment]
Sorry, I don't use Zotero and know next to nothing about its `biblatex` export. I do know, however, that "Better BibTeX for Zotero" (https://retorque.re/zotero-better-bibtex/) makes it possible to tweak the Zotero export quite a bit and found https://retorque.re/zotero-better-bibtex/exporting/extra-fields/ on the homepage which seems like it could help. But maybe there is a more elegant way if Zotero has a marker for newspaper/non-academic articles vs journal/academic articles that could be leveraged here.
