### ISSUE TITLE
Upgrade CTAN package 

### ISSUE THREAD

**Issue by msrn** [plk/biblatex-apa#145]
As of currently the package in CTAN is [v9.14 from 2020-08-28](https://ctan.org/pkg/biblatex-apa). However current master branch includes many changes and additions which in my opinion warrants for a new release.

**Comment by msrn** [comment]
This is much needed as TexLive 2022 includes this package, and package updates for the new release are frozen in March 10, 2022.

**Comment by plk** [comment]
I will make a new release in the next few days.

**Comment by netique** [comment]
I do not see any updates. Am I missing something? TeXLive 2022 tlmgr gives a warning about starred `\DeclareDelimAlias`. Manual installation from GitHub solves the issue, as it has been already solved many months ago, of course.

**Comment by msrn** [comment]
> I do not see any updates. Am I missing something? TeXLive 2022 tlmgr gives a warning about starred `\DeclareDelimAlias`. Manual installation from GitHub solves the issue, as it has been already solved many months ago, of course.

The package on CTAN was updated on 2021-12-24 according to this commit. https://github.com/plk/biblatex-apa/commit
/fb08d8ab720fe75e6df60a20736754f63f6164ff

And on Jan 7, 2022 https://github.com/plk/biblatex-apa/commit/6e66dfb0af04502a3a2757cec1e6261c4ea4669d that issue was fixed, so it isn't included in the CTAN package.
