### ISSUE TITLE
Website name as title addendum (instead of separate field)

### ISSUE THREAD

**Issue by otopkron** [plk/biblatex-apa#154]
Hello,
I use this code:

%BibTex Library
\usepackage[
backend=biber,
style=apa,
natbib=true,
]{biblatex}
\addbibresource{References.bib}

and for example this bib entry:

@online{noauthor_afghanistan_2021,
	title = {Afghanistan conflict: Kabul falls to Taliban as president flees},
	url = {https://www.bbc.com/news/world-asia-58223231},
	shorttitle = {Afghanistan conflict},
	abstract = {The Islamist group has claimed victory in Afghanistan, as residents and diplomats try to escape.},
	titleaddon = {{BBC} News},
	urldate = {2022-01-30},
	date = {2021-08-16},
	langid = {british},
	file = {Snapshot:/home/felix/Zotero/storage/54TASRG7/world-asia-58223231.html:text/html},
}

and get (title correctly italic):

Afghanistan conflict: Kabul falls to taliban as president flees [BBC news]. (2021, August 16). Retrieved
January 30, 2022, from https://www.bbc.com/news/world-asia-58223231

but it should, as far as I know, be this:

Afghanistan conflict: Kabul falls to taliban as president flees. (2021, August 16). BBC news. Retrieved
January 30, 2022, from https://www.bbc.com/news/world-asia-58223231

It would be totally awesome if this could be solved before I have to submit my bachelor's thesis... ;)
I'm completely new to Github so if this is the wrong format/forum, I apologize and am thankful for feedback.
Kind regards!

**Comment by moewew** [comment]
The example entries in https://github.com/plk/biblatex-apa/blob/master/bibtex/bib/biblatex-apa-test-references.bib all use `eprint` for the "website name".

I will admit that this is slightly counter-intuitive given the usual meaning of `eprint` in the `biblatex` data model, but the output seems to be what you want

```latex
\documentclass[american]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=apa]{biblatex}

\begin{filecontents}{\jobname.bib}
@online{noauthor_afghanistan_2021,
  title      = {Afghanistan conflict: Kabul falls to Taliban as president flees},
  url        = {https://www.bbc.com/news/world-asia-58223231},
  shorttitle = {Afghanistan conflict},
  eprint     = {BBC News},
  urldate    = {2022-01-30},
  date       = {2021-08-16},
  langid     = {british},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{noauthor_afghanistan_2021}

\printbibliography
\end{document}
```

> Afghanistan conflict: Kabul falls to taliban as president flees. (2021, August 16). BBC News. Retrieved January 30, 2022, from https://www.bbc.com/news/world-asia-58223231

**Comment by otopkron** [comment]
Perfect, thank you! It is a Zotero issue then, because it offers @titleaddon as "website title" and @eprint is not available.

**Comment by moewew** [comment]
I don't think we can or should say this is a bug in the Zotero exporter. The `biblatex` standard data model does not have a field for the website title (see also https://github.com/plk/biblatex/issues/1150), so if custom styles need something like this, they need to roll their own solution. Zotero can't possibly know what your style does, but I'm guessing there are ways to tell Zotero about this (I don't use Zotero, so I don't know how painful that is with vanilla Zotero, but from what I have heard it should be possible with https://github.com/retorquere/zotero-better-bibtex).
