### ISSUE TITLE
Group author abbreviations

### ISSUE THREAD

**Issue by pat-githubber** [plk/biblatex-apa#156]
Hello,

I would like to group author abbreviation according to the [The examples in the APA style guide](http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test.pdf):

![image](https://user-images.githubusercontent.com/87087327/154225286-0502e368-2d7c-4416-b29b-c340c1f757ef.png)

I checked the [Package documentation](http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa.pdf) and the [biblatex-apa-test.tex](https://github.com/plk/biblatex-apa/blob/master/doc/biblatex-apa-test.tex) but I cannot identify, how the group author abbreviation is generated. According to the given example, I assume that **The American Psychological Association** and **APA** are defined in the `bib` file.

So, How do I achieve group author abbreviation in practice?
Where and how is the full author (e.g. **The American Psychological Association**) and its abbreviation (**APA**) defined?

Thank you for this regard package!!

**Comment by moewew** [comment]
The long author names goes into the `author` field, the abbreviated form into `shortauthor`.

```latex
\documentclass[american]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=apa]{biblatex}

\begin{filecontents}{\jobname.bib}
@book{8.21a,
  author      = {{The American Psychological Association}},
  shortauthor = {APA},
  title       = {Title1},
  date        = {2017},
}
@book{8.21b,
  author      = {{The American Psychological Association}},
  shortauthor = {APA},
  title       = {Title2},
  date        = {2006},
}

\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{8.21a}

ipsum \autocite{8.21b}

dolor \autocite{8.21a}

\printbibliography
\end{document}
```

You can find many examples from the APA manual in https://github.com/plk/biblatex-apa/blob/master/bibtex/bib/biblatex-apa-test-references.bib and the examples from the `biblatex-apa` docs in https://github.com/plk/biblatex-apa/blob/master/bibtex/bib/biblatex-apa-test-citations.bib (note that `groupauthor` is an obsolete field that has been superseded by `author`: https://github.com/plk/biblatex-apa/pull/157).

**Comment by pat-githubber** [comment]
I haven't checked the sub-directory `master/bibtex/bib/` here at GitHub 🤦‍♂️  many thanks!!

After a quick research and try out, I discovered that neither Mendeley nor Zotero offers a `shortauthor` field.

- Mendeley web research: no results
- Mendeley on MacOS: Preferences -> Document Details -> Show fields: here, the field `shortauthor` is not listed
- Zotero Forum: `shortauthor` not available, see [Looking for short author field](https://forums.zotero.org/discussion/85943/looking-for-short-author-field)

How do you use/implement `shortauthor` in practice? I assume it is done manually?

I probably will use the available field `shorttitle` in Mendeley, and manually search&replace `shorttitle` with `shortauthor` in the final `bib` file after my paper is done. I know that this could be done automatically with a latex code, which runs every time I compile, but I am not that advanced to realize this, yet.

**Comment by moewew** [comment]
`shortauthor` is a field in the standard `biblatex` data model. So software claiming to support `biblatex` could be expected to support this field.

I curate my `.bib` files manually, so I don't know a lot about tools like Mendeley and Zotero. From what I have seen so far it can be a bit tricky to get Mendeley to produce high-quality `.bib` files. I'd expect that there is some way to get Zotero to support `shortauthor`, if push comes to shove via Zotero Better BibTeX (https://retorque.re/zotero-better-bibtex/).
