### ISSUE TITLE
nodate and other literals in danish-apa.lbx

### ISSUE THREAD

**Issue by Hen-Rex** [plk/biblatex-apa#161]
Hi @plk 

I noticed that a lot of the literals / bibliography strings in danish-apa.lbx have no translation and are marked with "% FIXME".

Also, the "nodate" string is missing entirely from danish-apa.lbx

Do you need help translating these into Danish and is there a reason why "nodate" is missing?

**Comment by Hen-Rex** [comment]
I tried adding "nodate" into danish-apa.lbx, but for some reason it does not make any difference? How come?
 
nodate           = {{s\adddot d\adddot}{s\adddot d\adddot}},

**Comment by plk** [comment]
Yes, if there are any `%FIXME`, this means any contribution to these translations is appreciated. `nodate` isn't defined by the APA style, it's a `biblatex` core localisation string - you'll find it in the `danish.lbx` in the `biblatex` distribution.

**Comment by Hen-Rex** [comment]
Hi

I have made the changes and fixed all Danish FIXME strings. I am not an avid user of Github so I don't know if I can just merge these changes?

As for "nodate", it does appear in the biblatex danish.lbx file, but documents still write "nodate" in the list of references despite of this:

    \DeclareLanguageMapping{danish}{danish-apa}


Looking at spanish-apa.lbx of the biblatex-apa package - it also has a separate "nodate" string. If I declare my language mapping to spanish-apa it works (but in Spanish):

    \DeclareLanguageMapping{danish}{spanish-apa}



I have tried adding a nodate translation in danish-apa.lbx, but it does not work.
Editing nodate in spanish-apa.lbx does work. So I don't know why Spanish works, but not Danish.





Henrik Stougaard
Technical Writer & Compliance		
Bricksite ApS <https://bricksite.dk/>
CVR 29408378 • Normansvej 1 • 8920 Randers NV
 
CONFIDENTIAL: This email, including attached files, may contain confidential information and is intended only for the use of the individual and/or entity to which it is addressed. If you are not the intended recipient, disclosure, copying, use, or distribution of the information included in this email is prohibited. Please delete this email immediately and notify us by replying to this email.

**Comment by plk** [comment]
In github, you can just make a "pull request" that I can merge. Are you using the latest APA style version? You don't need the `\DeclareLanguageMapping` and this may just override the biblatex strings if they are present (spanish is an anomaly) which explains the issue you are seeing.

**Comment by Hen-Rex** [comment]
I have made the pull request now. I added the "nodate" literal, but could not figure out how to edit the commit since it did not allow me to do so.

I have an additional question.
biblatex's standard danish.lbx file already contains references to:

- mathesis
- candthesis
- phdthesis

But danish-apa.lbx only references:
- mathesis
- phdthesis

Isn't that an issue? Should danish-apa.lbx and the remaining language files belonging to biblatex-apa drop its own translations in favor of the standard biblatex translations found in the normal biblatex repo?

**Comment by Hen-Rex** [comment]
But anyway, returning to the original issue: It prints "nodate" if there is not date defined. This is caused by this block of code found in apa.bbx:

`% Don't fall back on other year fields if there is no year, use
% "nodate" string
\DeclareLabeldate{%
  \field{pubstate}
  \field{date}
  \field{eventdate}
  \field{year}%legacy - no ISO8601 support
  \literal{nodate}
}`

For some reason it does not care that this literal is also defined in the language file in biblatex in danish.lbx.
The translations in danish.lbx (biblatex, not biblatex-apa) should overwrite the "nodate" string, no?

**Comment by Hen-Rex** [comment]
Yes, it seems the 'nodate' issue stems from an outdated version of biblatex-apa.lbx that I used. I updated to the latest version of biblatex and biblatex-apa, which seems to have resolved the issue.
