### ISSUE TITLE
Warn when `backend=bibtex`

### ISSUE THREAD

**Issue by tmalsburg** [plk/biblatex-apa#17]
Many users assume that either bibtex or biber can be used as the backend with biblatex.  However, bibtex is not anymore supported with the apa style.  When a user tries `backend=bibtex`, the error message is

    ! Undefined control sequence.
    l.231 \DeclareStyleSourcemap
                            {

which is very opaque.  Eventually, I found the relevant piece of information in the biblatex-apa documentation but it cost me a fair bit of time.

It think it would he helpful if biblatex-apa could emit a warning message when the user attempts to use bibtex.

By the way, thank you for biblatex, biblatex-apa, and biber.  It's a great pleasure to work with them.

**Comment by moewew** [comment]
The styles even use `\RequireBiber[3]` which throws an error that Biber is required. That message, however only comes after the first error about `\DeclareStyleSourcemap` not working, so for people that abort on first errors, `\RequireBiber[3]`  isn't particularly helpful (as its error comes only later). 

One could solve this problem by providing dummy definitions in `biblatex1.sty`/`biblatex_legacy.sty` that automatically call `\RequireBiber[3]`, so the error thrown by TeX is a bit more user friendly. But that of course requires replicating all Biber only commands in the legacy files for the sake of rerouteing.

**Comment by plk** [comment]
Please try biblatex 3.3/biblatex 2.4. I have moved this test at time of invocation so it should be caught when the `\RequireBiber` macro is run. You'll need biblatex-apa 6.8 for biblatex 2.4 (just submitted to CTAN).

**Comment by moewew** [comment]
It works great, the error message is exactly where I would expect it to be.

Thank you!
