### ISSUE TITLE
Single executive producer incorrectly identified as "Executive Producers"

### ISSUE THREAD

**Issue by ChristophSantel** [plk/biblatex-apa#182]
When citing a @Video-entry with only one executive producer, the plural term "Executive Producers" is incorrectly printed in the references section. Please see the minimum working example attached.

Thank you,
Christoph

P.S.: Feel free to reach out to christoph@santel.eu if additional clarification on the issue is needed.

[MWE.pdf](https://github.com/plk/biblatex-apa/files/8843604/MWE.pdf)
 [MWE.bib.txt](https://github.com/plk/biblatex-apa/files/8843612/MWE.bib.txt)
[MWE.tex.txt](https://github.com/plk/biblatex-apa/files/8843613/MWE.tex.txt)

**Comment by plk** [comment]
Will be fixed in next version. If you need this fix now, replace the `mainvideo` macro in `apa.bbx` with:


```
\newbibmacro*{mainvideo}{%
  \iffieldundef{maintitle}
    {}
    {\usebibmacro{in}%
     \printnames[apanames][-\value{listtotal}]{execproducer}%
     \setunit{\addspace}%
     \ifthenelse{\the\c@execproducer=1}%
       {\bibcplstring[\mkbibparens]{execproducer}}
       {\bibcplstring[\mkbibparens]{execproducers}}%
     \setunit{\addcomma\addspace}%
     \printfield{maintitle}}}

```

**Comment by ChristophSantel** [comment]
Hello,
the bug fix works and provides the desired results. Thank you!

**Comment by plk** [comment]
The annotation without a name index like `=execproducers` applies to the whole field and would naturally be plural but you can get what you want with `1=execproducer` - note the singular as individual list item roles are singular in the code. I can put a comment in about this in the examples.

**Comment by PsychicBirdy** [comment]
I see. Yes, the comment on that is really helpful, I believe. Thanks a lot!
