### ISSUE TITLE
Error with updated CTAN package?

### ISSUE THREAD

**Issue by samulicrum** [plk/biblatex-apa#185]
Hi,

the CTAN page shows version 9.16 (https://ctan.org/pkg/biblatex-apa), but for example the apa.bbx file is is still the 9,15 version both on the root mirror (http://dante.ctan.org) as well as in the archive that can be downloaded from the first URL. Do I miss something or did you not upload the 9.16 package?

Kind regards, 

samulicrum

**Comment by samulicrum** [comment]
Seems like there is a large delay between updates to the root server. The package on https://ctan.org/pkg/biblatex-apa has been updated by now.

**Comment by bhopmann** [comment]
I'm facing a similar issue: `tlmgr info biblatex-apa` shows version 9.16, but in fact all files are equivalent to version 9.15. I've tried reloading the package via `tlmgr` several times using different mirrors but without success. Manualy downloading the package (https://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-apa.zip) matches the correct version with the correct files.

**Comment by moewew** [comment]
https://tug.org/pipermail/tex-live-commits/2022-June/date.html suggests TeX Live pulled in the `biblatex` and Biber updates, but did not yet update `biblatex-apa`. Confusingly the catalogue was updated (https://tug.org/pipermail/tex-live-commits/2022-June/022329.html), so the catalogue info for `biblatex-apa` might show info new data from CTAN, but the package itself is not up-to-date with CTAN yet.

I suggest you wait until tomorrow and see if the real `biblatex-apa` update arrives on TeX Live. It it isn't updated tonight, this needs to be brought up on the TeX Live list (https://tug.org/mailman/listinfo/tex-live).

**Comment by samulicrum** [comment]
The package will be in the repo due tomorrow (https://tug.org/pipermail/tex-live/2022-June/048261.html)
