### ISSUE TITLE
Formatting issue with book reviews

### ISSUE THREAD

**Issue by Quaeeee** [plk/biblatex-apa#188]
A full stop seems to be missing for review entries without titles, when they are displayed in the reference list. (Sorry for nitpicking!)

Here's the MWE:

```
\documentclass{article}
\usepackage[style=apa]{biblatex}
\addbibresource{\jobname.bib}

\begin{filecontents}[force]{\jobname.bib}
@article{Craig1990-CRAKAT,
  author = {Edward Craig},
  publisher = {Oxford University Press},
  title = {Knowledge and the State of Nature},
  year = {1990},
}
@article{Steup1992-STEKAT-15,
  publisher = {Duke University Press},
  pages = {856},
  number = {4},
  volume = {101},
  author = {Matthias Steup},
  journal = {Philosophical Review},
  year = {1992},
  RELATED        = {Craig1990-CRAKAT},
  RELATEDTYPE    = {reviewof},
  RELATEDSTRING  = {Review of the book},}
\end{filecontents}

\begin{document}

\cite{Steup1992-STEKAT-15}

\printbibliography

\end{document}
```

This gives the following in the entry list:
<img width="794" alt="Screenshot 2022-08-11 at 9 53 31 PM" src="https://user-images.githubusercontent.com/65057337/184270636-df7ec78c-5594-4ae4-af86-b96dfd3ff823.png">

According to APA manual Section 10.7 and [this site](https://apastyle.apa.org/learn/faqs/reference-book-review), there probably should be a full stop after the year, i.e., 'Steup, M. (1992). [Revi....'.

The full stop is missing only if no title is given to the review article (which is often the case with reviews in journals, in philosophy at least). A workaround I found is adding `title = {\phantom{}}` in the `.bib` file (`title = {}` doesn't work, btw). This creates a little bit of extra space though.

**Comment by plk** [comment]
Thanks for pointing this out - fixed in source for next version. As a fix now, find your local copy of `apa.bbx` (run `kpsewhich apa.bbx`) and then replace line 1541 with:

```
  \printdelim{nametitledelim}\newblock
```

**Comment by Quaeeee** [comment]
That fixed it. Thanks for the quick response!
