### ISSUE TITLE
Indirect citation support

### ISSUE THREAD

**Issue by jrmoserbaltimore** [plk/biblatex-apa#189]
Either I can't find it in the docs or there's no support for [indirect citations](https://library.csp.edu/apa/secondary).  This is relatively straightforward so hopefully that's enough information to understand the issue.

Please add this, or add it to the docs, or point me at whatever I failed to properly read.  I'm interested in any limitations (does biblatex even have a citation command for indirect citations? I don't see one).

**Comment by plk** [comment]
Hmm ... I don't think there is a generic way to do this currently and it would have to be looked at as part of the style unless @moewew knows of a way to do this in a generic way?

**Comment by plk** [comment]
However, you can get this format manually:

```
\documentclass{article}
\usepackage[style=apa]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\nocite{springer}
This follows from \textcite[][as cited in Springer, 1950]{bertram}.
\printbibliography
\end{document}
```

We just don't allow nested citations currently so no citation commands in postnotes.

**Comment by moewew** [comment]
This also depends heavily on how you want to treat the secondary and primary source in terms of the bibliography.

The main problem is what @plk already mentioned: you can't nest citation commands, so something like

```latex
This follows from \textcite[][as cited in \nptextcite{sigfridsson}]{bertram}.
```
won't work.

For specific use cases you can cook up specific solutions, e.g. https://tex.stackexchange.com/q/27964/35864, but I'm not sure if within the current framework there is something that would be universal and flexible enough.
