### ISSUE TITLE
uri field is not set in verbatim mode

### ISSUE THREAD

**Issue by bastorran** [plk/biblatex-apa#19]
Hello,
I encountered a problem using biblatex-apa. The uri field is not set in verbatim mode, at least in conjunction with lualatex and polyglossia set to german.

Minimal working example:
```
\documentclass{scrartcl}

\usepackage{polyglossia}
\usepackage{fontspec}
\usepackage{microtype}
\usepackage{hyperref}
\usepackage{csquotes}
\usepackage[backend=biber,style=apa]{biblatex}

% Polyglossia language options
\setdefaultlanguage{german}

% Biblatex options
\DeclareLanguageMapping{german}{german-apa}
\addbibresource{quellen.bib}
\nocite{*}

\begin{filecontents}{quellen.bib}
  @Manual{R-base,
      title = {R: A Language and Environment for Statistical Computing},
      author = {{ R Development Core Team}},
      organization = {R Foundation for Statistical Computing},
      address = {Vienna, Austria},
      year = {2008},
      isbn  = {3-900051-07-0},
      url = {http://www.R-project.org},
    }
\end{filecontents}

\begin{document}
  \printbibliography
\end{document}
```
Thanks for your help!

**Comment by plk** [comment]
Can you be more specific? Do you mean the font or the .bbl? In the .bbl, it is verbatim:

```
      \verb{url}
      \verb http://wwwR-projectorg
      \endverb
```

If you mean the font, that's a style issue and best asked on tex.stackexchange.com

**Comment by bastorran** [comment]
Thanks for your fast reply. So I tried a bit more and created an even shorter
example (doesn't matter whether compiled with LaTeX or LuaLaTeX):
```
\documentclass{scrartcl}

\usepackage[style=apa]{biblatex}

\begin{document}

  \verb|Test output| \\ \url{https://www.test.com}

\end{document}
```
If I run this without the `style` argument I get the correct verbatim font for
the url. With `style=apa` it gives me the undesired output. I assume that
biblatex-apa is defining an url command (as without the package, the command
doesn't exist) without setting font to verbatim.

This cannot be undone by loading hyperref later.

**Comment by plk** [comment]
Yes, this is by design in the apa style package as the APA manual does not use fixed-width fonts for urls. I prefer fixed-width fonts for urls but users complained that it didn't follow the style. You can probably change this with:

```
\DeclareFieldFormat{url}{\texttt{\url{#1}}}
```

or similar in your preamble - ask on tex.stackexchange.com

**Comment by bastorran** [comment]
Okay, thanks for your help! I wasn't aware about this fact.
