### ISSUE TITLE
"labelday" thing...

### ISSUE THREAD

**Issue by vieruodu** [plk/biblatex-apa#190]
Thanks for your work. I upload your apa.bbx to my overleaf project, it fixed the warning

> Package biblatex Warning: The starred command '\DeclareDelimAlias*' is deprecated. Use the unstarred version '\DeclareDelimAlias' instead.

However, after that, "labelday" thing turns out in my main text and reference list.

the normal output should be like `"Blau (1986)` or `Blau, 1986`
but now it turns to be `Blau (1986labelday)` or `Blau, 1986labelday`

as the reference part, the normal output should  be like

> Blau, P. M. (1986). Exchange and power in social life (2nd ed.). Routledge. https://doi.org/10.
4324/9780203792643

but now it turns to be

> Blau, P. M. (1986labelday). Exchange and power in social life (2nd ed.). Routledge. https://doi.org/10.
4324/9780203792643

My reference code is

`@book{Blau1986,
  title = {Exchange and Power in Social Life},
  author = {Blau, Peter M.},
  date = {1986},
  edition = {2},
  publisher = {Routledge},
  location = {New York},
  doi = {10.4324/9780203792643}
}`

my package use code is 
`\usepackage[style=apa,sortcites=true,sorting=nyt,backend=biber]{biblatex}`

my reference insert code is
`parencite{key}` or 'parencite*{key}'

I know I just need to modify your code a little bit, but I was so new to latex and under the thesis time pressure, I have no time to spend much time on fixing it by myself. So I come here to seeking help.

Thanks for your attention and patience.

**Comment by plk** [comment]
I would recommend posting to tex.stackexchange.com if you need a rapid response - that is a very active site for such questions with a lot of style and biblatex users on there.

**Comment by vieruodu** [comment]
> I would recommend posting to tex.stackexchange.com if you need a rapid response - that is a very active site for such questions with a lot of style and biblatex users on there.

thanks for your replay. I would try it.

**Comment by moewew** [comment]
Some `biblatex-apa` versions use cutting edge code from (at the time of release) current `biblatex` and Biber versions. If you upload (parts of!) `biblatex-apa` to your Overleaf project you risk running into incompatibilities between `biblatex-apa` and Overleaf's `biblatex` and Biber versions.

If you upload a recent version of `biblatex-apa`, you definitely want to select the newest TeX live Overleaf have to offer. But this may not be enough. If your only reason for wanting a new `biblatex-apa` is to avoid the harmless warning, then frankly I wouldn't bother.
