### ISSUE TITLE
Film surrounded by quotes instead of being italicized with \citetitle

### ISSUE THREAD

**Issue by misilot** [plk/biblatex-apa#193]
Hello,

When using `\citetitle{}` the out put is `"The Public"` instead of _The Public_.

Example bib entry

```
@VIDEO{the-public,
	ENTRYSUBTYPE   = {film},
	AUTHOR         =  {Emilio Estevez},
	AUTHOR+an:role = {1=director},
	TITLE          = {The Public},
	PUBLISHER      = {Hammerstone Studios, Living the Dream Films, E2 Films},
	DATE           = {2018},
}
```

Is there an easy way to fix this, or should I just type out the Title?

Thanks!

**Comment by plk** [comment]
You should be able to put this in your preamble:

```
\DeclareFieldFormat{citetitle}{\mkbibemph{#1}}
```

However, if you have some evidence that this is a general issue and it should always look like this, it can be changed in the next version. Looking at the current code, quotes around the title when citing on the title are there on purpose which looks like it was done on purpose. If you can find something in the APA 7th to contradict this, let me know.

**Comment by misilot** [comment]
I tweeted at apa_style to see if they can provide any guidance, and just got it back -- https://twitter.com/APA_Style/status/1572699756698439681

>Good question! You can tell by the format in the reference. Titles italicized in references are italicized in text; titles not italicized in references are in quotation marks in text. For example, book titles in text are italicized, but journal article titles in text use quotes.

**Comment by plk** [comment]
In that case, this should fix it in your preamble:

```
\DeclareFieldFormat[book,manual,report,periodical,legmaterial,jurisdiction,video]{citetitle}{\mkbibemph{#1}}
```

If that works, I'll update for the next version.

**Comment by misilot** [comment]
Thanks @plk! This worked great!
