### ISSUE TITLE
Corrección para español APA7

### ISSUE THREAD

**Issue by Ronaldr3UC** [plk/biblatex-apa#195]
Quiero que consideren la posibilidad de corregir en el paquete algunos detalles para la traducción al español.

1. El ampersand (&) en las referencias y citas debe remplazarse por la letra "y"
2. El no date (n.d) en referencias y citas debe remplazarse por "s.f"
3. En las referencias con tres o mas autores, quitar la coma después del antepenúltimo autor.

En el archivo adjunto tengo algunos códigos que corrigen estos errores pero sería bueno que se pudieran  articular estas mejoras en el paquete para español. No soy el autor de esos códigos pero circulan en foros. 

Gracias

[Código para referencias APA7 Latex.txt](https://github.com/plk/biblatex-apa/files/9689477/Codigo.para.referencias.APA7.Latex.txt)

**Comment by plk** [comment]
Can you post an example of these issues on tex.stackexchange.com? There you will get rapid help on this - these issues should already be addressed in the `biblatex` package Spanish localisation and so we'll need to see examples of them not working correctly.

**Comment by rmolina** [comment]
@Ronaldr3UC: You are using an old version; please update the package. Current releases work very well for Spanish. Also, see #136 for a previous discussion about the ampersand in Spanish. In particular, see the Errata to the translation published by Manual Moderno: We should use ampersands even in Spanish (Yes, this is new in APA 7).
