### ISSUE TITLE
in spanish, biblatex-apa takes "¿" symbol into account when ordering references

### ISSUE THREAD

**Issue by daolchang** [plk/biblatex-apa#197]
Hello, I came across this issue because of multiple references with sameauthor and sameyear where a reference starting with "¿Que..." was put at the top when the "Q" should have been taken into account. More details in this post: https://tex.stackexchange.com/questions/667573/biblatex-seems-to-take-into-account-symbols-when-ordering-sameauthor-sameyear-re/667594#667594

The solution proposed definitely fixed it, but it is something that would be very useful to incorporate for compatibility with language localizations or rare titles that use other symbols. Also for a bilingual spanish/english reference list, this would take care of the "¿" issue as well as the leading words in spanish that according to APA 7th should be excluded from ordering.

\DeclareNosort{
	\nosort{setnames}{\regexp{\p{General_Category=Punctuation}}}
	\nosort{settitles}{\regexp{\A\p{General_Category=Punctuation}+}}
	\nosort{settitles}{\regexp{\A(?:The|An|A|El|La|Los|Las)\s+}}
}

Thanks in advance!

**Comment by plk** [comment]
This is exactly why the `\DeclareNosort` macro exists but we can't really put in much in the way of default settings for this as it is very language/application specific, as you have proven ...
