### ISSUE TITLE
eprint fields are ignored (?)

### ISSUE THREAD

**Issue by nkr0** [plk/biblatex-apa#198]
Are `eprint` fields ignored in apa style?
```
@article{test,
 author = "author",
 journal = "journal",
 title = "Title",
 eprinttype = "jstor",
 eprint = "1",
 url = "https://www.jstor.org/stable/1",
 year = "2000"
}
```
In the default style the eprint info gets formatted as "JSTOR: [1](http://www.jstor.org/stable/1)". In APA style  this is completely ignored.

In APA, a DOI is shown as a regular url. Perhaps, we could also show eprint info as regular urls. So for the JSTOR eprint in APA we could add
```
\DeclareFieldFormat{eprint:jstor}{%
  \ifhyperref
    {\href{https://www.jstor.org/stable/#1}{\nolinkurl{https://www.jstor.org/stable/#1}}}
    {\nolinkurl{https://www.jstor.org/stable/#1}}}
\DeclareFieldAlias{eprint:JSTOR}{eprint:jstor}
```

**Comment by plk** [comment]
`EPRINT` is only used in `ONLINE` entry types in the style (see the examples `.bib` files that come with the style. APA style now basically allows URLs for any type and doesn't have any special syntax for known online repositories like JSTOR.

**Comment by nkr0** [comment]
I didn't know that `EPRINT` is used only in `ONLINE`. However, I don't like the result when I use `EPRINT`s and `URL`s together for a bib entry. When using APA style only the `URL` is printed. Because `EPRINT` fields are ignored.
![image](https://user-images.githubusercontent.com/42086312/209706336-19c1eb02-003c-4c9d-bd55-a7dcc281a61a.png)
But in the regular style, both the `EPRINT` and `URL` prints repetitive info. I could remove `EPRINT` altogether but sometimes that is the output you want to have, and not a full `URL`
![image](https://user-images.githubusercontent.com/42086312/209706485-0aad261f-d09a-4611-82ec-3a9004698b2e.png)
It's a bit of a hassle to add/remove fields when switching between styles.

**Comment by plk** [comment]
You can use sourcemaps to delete data dynamically based on various conditionals, see the biblatex manual.
