### ISSUE TITLE
APA, duplicity of authors show name

### ISSUE THREAD

**Issue by maviva** [plk/biblatex-apa#204]
In the case that there are two references with the same pattern of first and last names for an author, but in one of the two references only one of the names appears, the result is that the names of the authors are shown. This is not correct in APA format.

Here's an example:

```
\documentclass[]{article}
\usepackage[style=apa,backend=biber]{biblatex}
\addbibresource{bib.bib}

\begin{filecontents}{bib.bib}
	@book{a1234t,
		title={title title title},
		author={Surname1 Surname2, Name1 Name2},
		year={1234},
		publisher={publisher publisher}
	}
	
	@book{a5678t,
		title={title title title},
		author={Surname1 Surname2, Name1},
		year={5678},
		publisher={publisher publisher}
	}
\end{filecontents}
\addbibresource{bib.bib}

\begin{document}

\parencite{a1234t} \\
\textcite{a1234t} \\
\cite{a1234t} 

\parencite{a5678t} \\
\textcite{a5678t} \\
\cite{a5678t} 

\end{document}
```

Output:
(N. N. Surname1 Surname2, 1234)
N. N. Surname1 Surname2 (1234)
N. N. Surname1 Surname2, 1234
(N. Surname1 Surname2, 5678)
N. Surname1 Surname2 (5678)
N. Surname1 Surname2, 5678

**Comment by plk** [comment]
Can you say where in APA 7 that this is said to be incorrect?

**Comment by maviva** [comment]
That's right, `style=apa`

**Comment by moewew** [comment]
I think PLK was asking for a reference in the APA manual that explicitly states that in this case the initials are wrong.

AFAICS `biblatex` simply thinks that `Surname1 Surname2, Name1 Name2` and `Surname1 Surname2, Name1` are two different people. This means that according to APA rules, they must be distinguished by their initials (see https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/citing-authors-same-surname). This assumption might be wrong, but it is hard to blame `biblatex` for it. The linked APA style site does not explicitly mention this case, so further investigation might be required.

**Comment by plk** [comment]
Please see pages 6 and 7 of the `biblatex-apa` style manual where this is described in detail with all examples from the 7th edition manual. This is mandatory for "lead" authors.
