### ISSUE TITLE
Hardcoded comma in url specification

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex-apa#21]
The `url+urldate` bibmacro inserts a hardcoded comma between `urldate` and the `from` bibstring. This conforms to the English APA guidelines (as in: "retrieved [date], from"), but is not correct in some localisations (at least in German, there should not be a comma: "Zugriff [date] unter").

I suggest to add a macro `\urldatecomma` (or somesuch) that can be modified in the lbx.

**Comment by plk** [comment]
Done, this will be in 7.0.

**Comment by jspitz** [comment]
Thank you! I suppose austrian should also be included to the varieties that use the `\addspace` only.

**Comment by plk** [comment]
Ah, I did naustrian but not austrian. Fixed now.
