### ISSUE TITLE
Dutch: "andothers" is translated as "e.a." instead of "et al."

### ISSUE THREAD

**Issue by LukeSerne** [plk/biblatex-apa#215]
Using Dutch as `mainlanguage`, citations with more than two authors are printed like `Lee e.a. (2013)` instead of `Lee et al. (2013)`. Using "et al." is recommended by several universities ([one](https://libguides.uvt.nl/apa-handleiding/meerdere-auteurs), [two (section 1.2.2.)](https://www.auteursrechten.nl/files/auteursrechten/2021-07/De%20APA-richtlijnen%20uitgelegd%20-%203e%20editie.pdf)).

I fixed this manually using the below latex command, but that shouldn't be necessary.
```latex
\DefineBibliographyStrings{dutch}{
    andothers={et al\adddot},  % e.a. -> et al.
}
```

**Comment by plk** [comment]
This needed to be fixed in biblatex as it's a standard localisation string.

**Comment by LukeSerne** [comment]
Yeah, I made an issue here because the recommendation to use "et al." comes from APA guides, so the use of "e.a." might be desirable in other styles. Either way, this works for me as well, so I'll close this issue.

**Comment by moewew** [comment]
I feel a bit funny about changes to core `biblatex` translations. Especially the "e.a." -> "et al." change has the potential to upset *a lot* of a documents. My default assumption is usually that translators chose the form we have now for a reason. Especially with "et al." I'm pretty sure they were aware of the alternative. Not sure if any of the original Dutch contributors are on GitHub and easily reachable, but I'd really like some feedback from other people before we go ahead with such a big change. (I feel similarly about the other changes to core `biblatex` translations, but "et al." is arguably the most noticeable.)

If changes are required for APA style, `biblatex-apa`'s `.lbx`s can override core strings as well.

**Comment by plk** [comment]
That's true, for some reason it didn't register. I will move it to APA.
