### ISSUE TITLE
Dutch: "nodate" is translated as "g.d." instead of "z.d."

### ISSUE THREAD

**Issue by LukeSerne** [plk/biblatex-apa#217]
`z.d.` as an abbreviation of `zonder datum` is recommended by [UvT](https://libguides.uvt.nl/apa-handleiding/webpagina#s-lg-box-15949952).

I manually fixed this by including the below command in my `.tex` file, but that shouldn't be necessary.
```latex
\DefineBibliographyStrings{dutch}{
    nodate={z\adddot d\adddot},  % g.d. -> z.d.
}
```

**Comment by plk** [comment]
Fixed in `biblatex` as it's a standard localisation string.

**Comment by LukeSerne** [comment]
It's fixed - thanks!
