### ISSUE TITLE
Dutch: Date inaccuracies

### ISSUE THREAD

**Issue by LukeSerne** [plk/biblatex-apa#219]
**Description**
When using the latest `dutch.lbx` file, there are some inaccuracies with printing dates and date ranges. The below MWE can be 

**MWE**
```latex
\documentclass{report}

\usepackage[dutch]{babel}
\usepackage[style=apa, backend=biber]{biblatex}

\begin{filecontents}[overwrite]{test.bib}
@online{DateMonthExample,
    author = {Tes, Terry},
    date = {2001-09},
    title = {Date month example},
    url = {https://www.example.com},
}
@online{DateRangeDaysExample,
    author = {Tes, Terry},
    date = {2002-09-01/2002-09-02},
    title = {Date range days example},
    url = {https://www.example.com},
}
@online{DateRangeMonthsExample,
    author = {Tes, Terry},
    date = {2003-08/2003-09},
    title = {Date range months example},
    url = {https://www.example.com},
}
\end{filecontents}
\addbibresource{test.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}

```
**Observed output**
The MWE outputs the bibliography as follows (recreated in markdown):

---
Tes, T. (2001 september). _Date month example_. https://www.example.com
Tes, T. (2002, 1 september–2). _Date range days example_. https://www.example.com
Tes, T. (2003 augustus– september). _Date range months example_. https://www.example.com

---

**Expected output**
I expected the dates to look as indicated below. I have highlighted the changes in bold.

---
Tes, T. (2001<b>,</b> september). _Date month example_. https://www.example.com
Tes, T. (2002, <b>1–2</b> september). _Date range days example_. https://www.example.com
Tes, T. (2003<b>,</b> augustus–september). _Date range months example_. https://www.example.com

---
In words:
(i) there should be a comma after the year in all of the examples;
(ii) when a date range is contained in a single month, the endash and second day-number should come before the month name; and 
(iii) if the range is between months, there should not be a space after the endash.

**Comment by LukeSerne** [comment]
Thanks for the quick fix. The first and third example look great with the latest version. The date in the second example is typeset as `(2002, september 1–2)` though, which should be `(2002, 1–2 september)` - the day range should come before the month.

**Comment by plk** [comment]
Should be correct now.

**Comment by LukeSerne** [comment]
Yeah, looks great. Thanks!
