### ISSUE TITLE
German tweaks

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex-apa#22]
I don't know if the APA itself has something to say about how to treat localizations. If not, I would suggest to follow the rules of the German Psychological Association (DGPs), which include slight modifications to the APA for German. See 
http://homepage.univie.ac.at/harald.werneck/Richtlinien_zur_Manuskriptgestaltung.pdf

This would require the following changes in the Germanic localization:
```
andothers = {et al\adddot}% instead of "u.\,a."

\def\finalandcomma{}% no comma after final and in German

\renewcommand{\apashortdash}{~}% "im Druck a", not "im Druck-a"
```

**Comment by plk** [comment]
Yes, I think this is a good idea. I have done this for Austrian and German. Perhaps you can try it. If you need a bundled zip of the release, let me know.

**Comment by jspitz** [comment]
It works as expected. Thanks.

**Comment by moewew** [comment]
I just noticed the thing with the serial comma, which is unusual in German and found commit https://github.com/plk/biblatex-apa/commit/fbf393e16397c9ed0f5b807b894b4147c187b1f9 which seems to introduce the serial comma for many languages, I'm not sure if all of them would actually use a serial comma.

**Comment by buhtz** [comment]
This problem affects me, too.

Old (Sept 2014) code of biblatex-apa worked fine for me. But now I have the problem with that comma. This is definitly against german citing rules.
Would be glad to see this fixed in the next release.

**Comment by plk** [comment]
Actually, this is already corrected in 7.0 dev - someone submitted a patch for german/austrian a few days ago.

**Comment by moewew** [comment]
My point was rather that the commit enabled the Oxford comma for other languages besides German as well.

I speak none of the other languages sufficiently well to judge if they use the Oxford comma, but I would be surprised if it were the norm in all those languages. Wikipedia, for example, lists French and Dutch amongst the languages where the Oxford comma is not the norm (https://en.wikipedia.org/wiki/Serial_comma#Other_languages).

**Comment by plk** [comment]
I am not sure why that was added now. It does seem odd, I need to do some testing.

**Comment by plk** [comment]
You are right, I have no idea why this happened - APA should pick up the biblatex language defaults which are all correct. I have removed this from all lbx files.
