### ISSUE TITLE
Release version 7.0

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#26]
Since `biblatex` 3.5 has arrived on CTAN, are there any plans to release version 7.0 soon?
Version 6.9 will throw errors when run on `biblatex` 3.5, this has already caused some grievance on TeX.SX [style=apa causes bibliography to fail](http://tex.stackexchange.com/q/329411/35864).

**Comment by plk** [comment]
v7 of the style is just submitted to CTAN.

**Comment by moewew** [comment]
Brilliant! Thank you. I'll update my answer accordingly.
