### ISSUE TITLE
DeclareLabeldate incomplete or buggy

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex-apa#27]
Not sure if this is an upstream bug (I had to do the same in one of my own style files), but with biblatex 3.5, you need to add `\field{year} `to the `\DeclareLabeldate` definition in `biblatex-apa` in order to get a proper year (rather than "nodate").

```
\DeclareLabeldate{%
  \field{pubstate}
  \field{date}
  \field{year}% <-- added this one
  \literal{nodate}
}
```

**Comment by plk** [comment]
Correct, thanks. I will publish v7.1 shortly along with biblatex 3.6 to address your other issues.
