### ISSUE TITLE
Reviews of more than one book, and books with editors

### ISSUE THREAD

**Issue by njbart** [plk/biblatex-apa#29]
MWE, using slighty modified examples from biblatex-apa-test-references.bib:

```
\documentclass{article}
\usepackage[american]{babel}
\usepackage[backend=biber, style=apa]{biblatex}
\DeclareLanguageMapping{american}{american-apa}

\usepackage{fontspec}
\setmainfont{Linux Libertine}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@REVIEW{7.06:45-mod,
  AUTHOR         = {B. R. Schatz},
  TITLE          = {Learning By Text or Context?},
  REVIEWTEXT     = {the book},
  RELATED        = {brdu,7.02:18},
  RELATEDTYPE    = {reviewof},
  RELATEDSTRING  = {Review of the books},
  JOURNALTITLE   = {Science},
  VOLUME         = {290},
  PAGES          = {1304},
  DATE           = {2000-11-17},
  DOI            = {10.1126/science.290.5495.1304},
}
@BOOK{brdu,
  AUTHOR     = {John Seely Brown and Paul Duguid},
  TITLE      = {The Social Life of Information},
  DATE       = {2000},
  PUBLISHER  = {Harvard Business School Press}
}
@BOOK{7.02:18,
  EDITOR         = {M. A. Shotton},
  TITLE          = {Computer Addiction? A Study of Computer Dependency},
  LOCATION       = {London, England},
  PUBLISHER      = {Taylor \& Francis},
  DATE           = {1989}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}

\cite{7.06:45-mod}

\printbibliography
\end{document}
```

Actual output:

![screen shot 2016-10-21 at 21 55 54](https://cloud.githubusercontent.com/assets/2765811/19611344/d2724bb0-97d0-11e6-8d5f-9e9d91a7038e.png)

Expected output:

> … [Review of the books _The social life of information_ by J. S. Brown & P. Duguid, 2000 and _Computer addiction? a study of computer dependency_, edited by M. A. Shotton, 1989] …

**Comment by plk** [comment]
This whole system has been overhauled for the 7th edition conformant release (version 9.0) , please check this.

**Comment by njbart** [comment]
Great. Now, this is what I get from my source above with version 9.0:

 ![apa](https://user-images.githubusercontent.com/2765811/69493290-11d84400-0ea5-11ea-8c13-372faf21dee1.png)

Since the 6th ed. of the APA manual (7.06, in particular) seems to be silent on reviews of more than one item, and I don’t have a copy of the 7th. ed. (yet), I can’t be 100% sure, but I feel there shouldn’t be a line break inside the entry but rather some connecting phrase like “, and”. 

Also, “Shotton” still isn’t labelled as editor.

Finally, in “Computer addiction? a study of computer dependency”, shouldn’t the “a” at the start of the subtitle be capitalized?

**Comment by plk** [comment]
This is all being address in for the 9.1 release soon. The "a" capialisation won't be however as this is normal - APA forces "sentence case" which means you have to protect the first letter of sentences after the first sentence in a field.  "{A}".

The line-break was a mistake, just defaulting the default `relateddelim` which will be reset to a command and space in 9.1.

**Comment by plk** [comment]
9.1 has just been sent to CTAN - please have a look at this and update.
