### ISSUE TITLE
German localization issues

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex-apa#31]
Where are the bibstrings `typechair` and `typechairs` supposed to be used? The German translations are definitely wrong ("Konferenzstuhl" literally translates "chair" as a seating furniture), but I'd need the context in order to decide on an appropriate translation (I suppose it should be something such as "Konferenzleitung" or "Konferenzmoderation", referring to a person who chairs a conference or session).

I am also not sure whether `producer`, `execproducer`, `director` and `writer` are really translated properly. Again, this depends on the context where they are supposed to be used.

**Comment by jspitz** [comment]
I have done some research and will come up with some proposed corrections as soon as https://github.com/plk/biblatex-apa/pull/30 has been handled.

See https://github.com/jspitz/biblatex-apa/commit/2285a1575c906437876f2b4a0ffd4a499c5921a4

**Comment by jspitz** [comment]
Fixed.by https://github.com/plk/biblatex-apa/commit/5efe14eafb43d8887ee846a6b470dca023e4d480

**Comment by moewew** [comment]
@plk Sorry to abuse this issue.

@jspitz Could you check the DPG guidelines regarding German dates with a year and month (and day)? There was a question on TeX.SX (https://tex.stackexchange.com/q/417648/35864) that suggests that the German localisation should also place a comma after the year.
> Clay, R. (2008, Juni). ...

**Comment by jspitz** [comment]
Yes, that's correct. The comma is required.

**Comment by moewew** [comment]
Thank you very much for checking this. What would full dates look like? (2000, 6. Juni)?

**Comment by jspitz** [comment]
The guidelines say nothing about full dates, AFAICS. The relevant passage reads:
> Bei Zeitungen und Magazinen ohne Bandangaben ist der Monat, die Jahreszeit oder eine andere Spezifizierung in der Klammer nach der Jahreszahl anzuführen.
>  Beispiel:
(1994, April)

(i.e., the month or something else such as the term has to be given in the date of journals that do not have a volume or number specification)

**Comment by jspitz** [comment]
> I assume
> 
>     (1994, 8. Juli)
> 
> would look more natural than
> 
>     (1994, Juli 8.)
Yes, definitely.

> Do you want me to submit a pull request for the date macros, or would you like to do that yourself?

Please go ahead. Thanks.
