### ISSUE TITLE
Booktitle capitalisation in @proceedings and @inproceedings

### ISSUE THREAD

**Issue by jamesdibley** [plk/biblatex-apa#32]
7.04.38 and 7.04.39 do not seem to render the conference title in line with my digital edition of the APA Publication Manual, 6th ed.
MWE: 
```
\documentclass{article}
\usepackage[british]{babel}
\usepackage[backend=biber, style=apa]{biblatex}
\DeclareLanguageMapping{british}{british-apa}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@PROCEEDINGS{7.04:38,
  AUTHOR         = {S. Herculano-Houzel and C. E. Collins and P. Wong and J. H. Kaas and R. Lent},
  TITLE          = {The Basic Nonuniformity of the Cerebral Cortex},
  BOOKTITLE      = {Proceedings of the National Academy of Sciences, {USA}},
  VOLUME         = {105},
  PAGES          = {12593--12598},
  DATE           = {2008},
  DOI            = {10.1073/pnas.0805417105}
}
@INPROCEEDINGS{7.04:39,
  AUTHOR         = {I. Katz and K. Gabayan and H. Aghajan},
  TITLE          = {A Multi-touch Surface Using Multiple Cameras},
  EDITOR         = {J. Blanc-Talon and W. Philips and D. Popescu and P. Scheunders},
  MAINTITLE      = {Lecture Notes in Computer Science},
  VOLUME         = {4678},
  BOOKTITLE      = {Advanced Concepts for Intelligent Vision Systems},
  PAGES          = {97--108},
  LOCATION       = {Berlin, Germany},
  PUBLISHER      = {Springer-Verlag},
  DATE           = {2007},
  DOI            = {10.1007/978-3-540-74607-2_9}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{7.04:38}
\cite{7.04:39}
\printbibliography
\end{document}
```
The output produced is 
![screen shot 2016-11-23 at 22 17 26](https://cloud.githubusercontent.com/assets/6264552/20577392/b35a1186-b1ca-11e6-811c-32342e421ad7.png)

Whereas the example provided in APA 6th is
![screenshot_2016-11-23-21-56-51](https://cloud.githubusercontent.com/assets/6264552/20577434/ee258fd4-b1ca-11e6-9690-e6fa52a78616.png)

FWIW, I have been able to alter this behaviour in apa.bbx, but I haven't tested my changes thoroughly and am not too sure I understand how the code is structured. If it's helpful, though, I can provide details.

**Comment by plk** [comment]
Do you mean the capitalisation?

**Comment by jamesdibley** [comment]
Yes.

**Comment by plk** [comment]
Well, normally that is dealt with with brace protection in the .bib file.

**Comment by jamesdibley** [comment]
That's a workaround I have used extensively, but it becomes a laborious and error-prone process when preparing submissions from other authors for publication. The behaviour is introduced by the package and it seems to me that a simple and permanent fix may be achieved there. If I am ignorant of a wider context here, please accept my apologies.

Presently the `@proceedings`, `@inproceedings`, `@inbook`, and `@incollection` drivers all use the same booktitle bibmacro, with the result that booktitle and booksubtitle fields are always printed in sentence case. As far as I can see, this is valid behaviour for 7.02, but not for 7.04.38 and .39. I experimented with introducing a macro to be used by the first two drivers:

```
   \renewbibmacro*{procbooktitle}{%
     \ifthenelse{\iffieldundef{booktitle}\AND\iffieldundef{booksubtitle}}
       {}
       {\printtext[booktitle]{%
          \mkbibemph{\printfield{booktitle}}%
          \setunit{\subtitlepunct}%
          \mkbibemph{\printfield{booksubtitle}}}%
        \setunit{\addspace}}%
     \printfield{booktitleaddon}}
```
and produced
![screen shot 2016-11-24 at 00 08 38](https://cloud.githubusercontent.com/assets/6264552/20580308/54605cfc-b1da-11e6-9991-b642665b0edb.png)
