### ISSUE TITLE
Captialize first word after Colon

### ISSUE THREAD

**Issue by Siedlerchr** [plk/biblatex-apa#33]
According to the style guide:

> When referring to books, chapters, articles, or Web pages, capitalize only the first letter of the first word of a title and subtitle, the first word after a colon or a dash in the title, and proper nouns. Do not capitalize the first letter of the second word in a hyphenated compound word. 
https://owl.english.purdue.edu/owl/resource/560/05/
http://blog.apastyle.org/apastyle/2011/06/capitalization-after-colons.html

For a fix, I found a reference to the IEEE biblatex style, which has the same guidance.

https://github.com/josephwright/biblatex-ieee/issues/17

**Comment by plk** [comment]
Many thanks. I have adapted the IEEE style solution and this will be in the next version.
