### ISSUE TITLE
missing space between month name and day in citation and reference when two dates are provided

### ISSUE THREAD

**Issue by Siedlerchr** [plk/biblatex-apa#34]
Hi,
there seems to be a problem with the handling of multiple dates for one entry.

biblatex-apa v. 7.2:

When I use `\textcite{Engelbart1984}`  in my text, I get: ...
...solutions in Engelbart (1984–March1).

And in the reference list:

> Engelbart, D. C. (1984, February 27–March1). Authorship provisions in augment.

Note the missing space after March.
I also have an entry with a single year-month-day date field, there the space after month is correctly set. 

The biblatex date is right according to the manual:

```
@InProceedings{Engelbart1984,
  author        = {Douglas C. Engelbart},
  title         = {Authorship Provisions in Augment},
  booktitle     = {COMPCON'84, Digest of Papers, Twenty-Eighth IEEE Computer Society International Conference},
  date          = {1984-02-27/1984-03-01},
  publisher     = {IEEE Computer Society},
  location      = {San Francisco, California, USA,},
  pages         = {465--472},
}
```

**Comment by plk** [comment]
Looking into it. For entries which are not citing dates for online resources, I think days should be dropped according to APA style. I have to verify this.

**Comment by Siedlerchr** [comment]
Thanks! 
I found a bit of info in the blog:
http://blog.apastyle.org/apastyle/2010/01/the-generic-reference-when.html

> Dates for magazines, newsletters, and newspapers should include “the year and the exact date of the publication (month or month and day),” according to the APA Publication Manual (6th ed., 6.28, p. 185). This means that the month should be given for monthlies, and the month and day for weeklies. If the periodical uses a season with the year, put the year, a comma, and the season in parentheses (2008, Early Spring).

and then:

> the determining factor is not whether they're called "journal" or "magazine" but how often they're published. In the case of these and other weeklies, use month, day, and year.

Additionally, I found some general helpful overview:
http://www.mtroyal.ca/library/files/citation/apa.pdf

**Comment by plk** [comment]
I've just uploaded version 7.4 to CTAN which should fix these issues.
