### ISSUE TITLE
Error with \enquote* in entry title

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex-apa#35]
I am not sure whether this is a biblatex-apa or a csquotes issue. Anyway, it you use `\enquote*` (only the starred version) in an entry title, LaTeX bails out with an error:
```
! Argument of \csq@qclose@ii has an extra }.
<inserted text> 
                \par 
l.26 
     
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

Runaway argument?
! Paragraph ended before \csq@qclose@ii was complete.
<to be read again> 
                   \par 
l.26 
     
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

! Missing } inserted
```
Minimal example:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{csquotes}
\usepackage{filecontents}

\begin{filecontents}{enquoting.bib}
	@article{test,
		title = {\enquote*{Enquoted Title}},
		journal = {A Journal},
		author = {John Doe},
		year = {2017},
		pages = {1--116},
	}
\end{filecontents}

\usepackage[english]{babel}
\usepackage[style=apa]{biblatex}
\DeclareLanguageMapping{english}{english-apa}
\addbibresource{enquoting.bib}

\begin{document}
	
\cite{test}

\printbibliography
	
\end{document}

```

**Comment by jspitz** [comment]
Further investigation revealed that it's `\MakeSentenceCase` (used here in `\DeclareFieldFormat{apacase}`) that does not play with `\enquote*` (probably an expansion problem).

Looks like it stumbles over the star, since the following does not yield the error:

```
\newrobustcmd\ienquote[1]{\enquote*{#1}}
...
title = {\ienquote{Enquoted Title}},
...
```

**Comment by jspitz** [comment]
@josephwright, do you have an idea maybe?

**Comment by jspitz** [comment]
Can I ask why this has been closed? INVALID? WONTFIX?

**Comment by a-nap** [comment]
I am having the same issue. Is there a known fix?

**Comment by jspitz** [comment]
At least the example given above meanwhile compiles without errors with a recent TeXLive. So the problem seems to have been addressed here or elsewhere.

**Comment by moewew** [comment]
Yes, the MWE shown above compiles without error with a current version of `biblatex` and Biber. (For example on [texlive.net](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%5Butf8%5D%7Binputenc%7D%0A%5Cusepackage%5Benglish%5D%7Bbabel%7D%0A%5Cusepackage%7Bcsquotes%7D%0A%0A%5Cusepackage%5Bstyle=apa%5D%7Bbiblatex%7D%0A%0A%5Cbegin%7Bfilecontents%7D%7B%5Cjobname.bib%7D%0A@article%7Btest,%0A%20%20title%20%20%20=%20%7B%5Cenquote*%7BEnquoted%20Title%7D%7D,%0A%20%20journal%20=%20%7BA%20Journal%7D,%0A%20%20author%20%20=%20%7BJohn%20Doe%7D,%0A%20%20year%20%20%20%20=%20%7B2017%7D,%0A%20%20pages%20%20%20=%20%7B1--116%7D,%0A%7D%0A%5Cend%7Bfilecontents%7D%0A%5Caddbibresource%7B%5Cjobname.bib%7D%0A%0A%5Cbegin%7Bdocument%7D%0A%5Ccite%7Btest%7D%0A%0A%5Cprintbibliography%0A%5Cend%7Bdocument%7D))

In v3.15 `biblatex` started using `expl3` code for case changing (https://github.com/plk/biblatex/pull/1005). This code is generally more robust and predictable than the previous implementation (not exactly always: https://github.com/plk/biblatex/issues/1050). I can no longer reproduce an error with `\enquote` or `\enquote*`.

If at all possible, please try to update your TeX distribution to obtain a current version of `biblatex` and Biber. If the error still occurs with an up-to-date `biblatex`, please show us a small example that reproduces the issue.

**Comment by a-nap** [comment]
It seems to have been an Ubuntu issue on my end that was causing all sorts of errors. Thank you!
