### ISSUE TITLE
Personal Communications

### ISSUE THREAD

**Issue by nbrewk** [plk/biblatex-apa#41]
As you are very likely aware, biblatex-apa does not accommodate for in-text citation of personal communications (APA manual section 6.20). I have come across [two possible solutions](https://tex.stackexchange.com/questions/87272/bibtex-or-biblatex-biber-private-communication-entry), but they do not integrate well into the biblatex-apa style specifically. So my actual workaround has been manually typing in these types of citations.

If a personal communication is added to a list of other in-text citations, there is no way to allow for automated alphabetical sorting, especially if the author's last name is between the letters of two other citations.

I am already using misc type in my bib for citing statutes.

Are there plans to include the personal communication as part of biblatex-apa?

**Comment by plk** [comment]
Not really as they are explicitly not to be included in any refence list. If you really want to do this, it's really outside of the scope of the APA style. As others mention - you can easily create a separate bib file dor these and then use standard biblatex mechanisms to display/sort them etc.
