### ISSUE TITLE
Printing of journal issue numbers

### ISSUE THREAD

**Issue by mutlusun** [plk/biblatex-apa#42]
Hello,

thanks for providing the apa style in biblatex! Recently I discovered that this style is always printing the journal issue number after the volume number. According to APA v6 this should only be done if the journal is paginated seperately by issue (see page 199 of the manual as well):

![apa0](https://user-images.githubusercontent.com/20613645/30157966-fed5b076-93c3-11e7-9d6f-7c2a0735d024.png)

So I created some little workaround:
```tex
\renewbibmacro*{journal+issuetitle}{%
  \usebibmacro{journal}%
  \setunit*{\addcomma\addspace}%
  \iffieldundef{series}
    {}
    {\newunit
     \printfield{series}
     \setunit{\addcomma\space}}%
  \printfield{volume}%
  \ifboolexpr{ test{\iffieldequalstr{journaltitle}{The Academy of Management Executive}} or
               test{\iffieldequalstr{journaltitle}{Another Journal}}}
    {\printfield{number}}%
    {}%
  \setunit{\addspace}\newblock
  \usebibmacro{issuename}%
  \newunit}
```
It is only checking for journals that have issues paginated seperately by issue. Before doing a real pull request I wanted to ask what do you think about this extension? I see following issues right now:
- only `journaltitle` is checked and not `journal`
- the jounals here are hardcoded. Is it possible to check a user created list instead? (Sorry, I'm no tex expert.)

Thanks!

**Comment by plk** [comment]
A better way to do this is by using the `biber` sourcemap feature. Add this to your preamble:

```
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
       \step[fieldsource=journaltitle,
             match=\regexp{(?:journal\stitle\sone|journal\stitle\stwo)}]
       \step[fieldset=number, null]
    }
  }
}
```

Where "journal title one" and "journal title two" are journals known to paginate across complete volumes. You don't need to care about the field `journal` as the default biblatex driver sourcemaps automatically convert this to `journaltitle` anyway.

I will add a note about how to do this in the next release documentation.

**Comment by mutlusun** [comment]
Hello,

thanks for your help and your suggestion! As I copied your example, it removed the number from all journals (regardless of the regex). But this solved my issue:
```tex
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
       \step[fieldsource=journaltitle,
             notmatch=\regexp{(?:The\sAcademy\sof\sManagement\sExecutive|My\sOther\sJournal)},
             final]
       \step[fieldset=number, null]
    }
  }
}
```

If I got the biblatex manual right, your `\step` was missing a `final` argument to jump out of the `map` directive. Or I missed something else ;-)

Regards
mutlusun

**Comment by plk** [comment]
You are probably right, thanks for checking.
