### ISSUE TITLE
Capital letters protected with {braces} displayed in lowercase

### ISSUE THREAD

**Issue by gcabanac** [plk/biblatex-apa#44]
This MWE featuring protected letters in the title of the reference outputs the letter ‘b’ of ‘beauties’ in lowercase.  This shouldn't be the case AFAIK.

I compiled it with:
- pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017)
- biber 2.9
- biblatex 2017/11/21 v3.9 programmable bibliographies (PK/JW/AB)
- apa.dbx 2017/11/05 v7.5 APA biblatex style data model
- english-apa.lbx 2017/11/05 v7.5 APA biblatex localisation
- english.lbx 2017/11/21 v3.9 biblatex localization (PK/JW/AB)
- american.lbx 2017/11/21 v3.9 biblatex localization (PK/JW/AB)
- all updates done _via_ TeX Live Utility 

It seems to me that protection with braces worked as expected with the current versions of pdfTeX and biber as of mid-October 2017.

```
\documentclass{article}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@article{vanRaan2004,
    author={van Raan, Anthony F. J.},
    title="{S}leeping {B}eauties in science",
    volume={59},
    DOI={10.1023/b:scie.0000018543.82441.f1},
    number={3},
    journal={Scientometrics},
    year={2004},
    pages={467--472}
}
\end{filecontents}

\usepackage[style=apa]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\cite{vanRaan2004}
\printbibliography
\end{document}
```

Am I missing something here?

Thank you.

**Comment by eivindhammers** [comment]
Capitalizing whole words seems to work in this example.

**Comment by gcabanac** [comment]
bibLaTeX behaves differently with `\usepackage[style=apa,language=french]{biblatex}` as it correctly typesets the protected in-word letter: “Sleeping Beauties in science”.

**Comment by plk** [comment]
Please can you try biber 2.10 from the "development" folder on Sourceforge.

**Comment by gcabanac** [comment]
With biber 2.10: it works like a charm!  The output appears as expected: “Sleeping Beauties in science.”
Thank you for digging into this.
