### ISSUE TITLE
Journal articles in special issues

### ISSUE THREAD

**Issue by eivindhammers** [plk/biblatex-apa#45]
When citing articles in special or supplementary issues, for which the `biblatex` manual suggests to use the `issue` field (implied on p. 20), the issue number appears in the text citation, but not in the references (I expected the reverse outcome). 

It works when using the `number` field instead, but Zotero BetterBiblatex will not let me export non-numeric issues to the `number` field. In any case, given the `biblatex` recommendation, the correct field should be `issue`. 

As per the [APA-style blog](http://blog.apastyle.org/apastyle/2012/05/citing-a-special-issue-or-special-section-in-apa-style.html), articles from supplementary issues should be cited and referenced as any other journal article, although necessarily tagged with the correct issue ("Suppl. 1" below). Hence, in the MWE below, I expect the reference entry to be

`Caselli, F. & Coleman II, W. J. (2013). On the Theory of Ethnic Conflict.
Journal of the European Economic Association, 11(Suppl. 1).` ,

but I get

`Caselli, F. & Coleman II, W. J. (2013). On the Theory of Ethnic Conflict.
Journal of the European Economic Association, 11.` ,

and I expect the citation

`(Caselli & Coleman II, 2013)` , 

but I get

`Caselli & Coleman II, 2013, Suppl. 1`

Compiled with XeLaTeX, biblatex-apa 7.5, biblatex 3.9, biber 2.9

```
\documentclass{article}
\usepackage{filecontents}
	
\begin{filecontents}{\jobname.bib}
@article{Caselli2013,
  title = {On the {{Theory}} of {{Ethnic Conflict}}},
  volume = {11},
  doi = {10.1111/j.1542-4774.2012.01103.x},
  issue = {Suppl. 1},
  journaltitle = {Journal of the European Economic Association},
  author = {Caselli, Francesco and Coleman II, Wilbur John},
  date = {2013},
}
\end{filecontents}

% Setup that I use, although not all options necessary here
\usepackage[
	backend=biber, 
	apamaxprtauth=30, 
	style=apa, 
	natbib=true, 
	doi=false,
	eprint=false, 
	labeldate=year]{biblatex}
	
\addbibresource{\jobname.bib}

\begin{document}
\citep{Caselli2013}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
In many cases you don't actually want `issue`, you want `number` instead. If you change `issue` to `number` in your MWE, things looks better.

**Comment by moewew** [comment]
See also
```latex
\documentclass{article}
\usepackage[backend=biber, style=apa]{biblatex} %  

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{fogliano_vitro_2011,
    langid = {english},
    title = {In Vitro Bioaccessibility and Gut Biotransformation of Polyphenols Present in the Water-Insoluble Cocoa Fraction},
    volume = {55},
    issn = {1613-4133},
    doi = {10.1002/mnfr.201000360},
    issue = {S1},
    journaltitle = {Molecular Nutrition \& Food Research},
    date = {2011-05-01},
    pages = {S44--S55},
    author = {Fogliano, Vincenzo and Corollaro, Maria Laura and Vitaglione, Paola and Napolitano, Aurora and Ferracane, Rosalia and Travaglia, Fabiano and Arlorio, Marco and Costabile, Adele and Klinder, Annett and Gibson, Glenn},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document} 
  \parencite{fogliano_vitro_2011}

  \printbibliography 
\end{document}
```
adapted from https://tex.stackexchange.com/q/414495/35864

It seems to me that the `issue` field should not pop up in citations and should instead be printed in the bibliography. I expect that `issue` should either behave as `number` or as in the standard styles.

**Comment by plk** [comment]
According to the current APA style, use `TITLEADDON` for this, not `ISSUE`. See the comments in the example .bib files that come with the style.

**Comment by moewew** [comment]
Mhhh. The examples `7.01:12a`/`7.01:12c` are entire issues (should they be `@article` or maybe better `@periodical` entries?). I don't think `titleaddon` can be used for single `@article`s since it is attached to `title` and not `journaltitle`.

Reading http://blog.apastyle.org/apastyle/2012/05/citing-a-special-issue-or-special-section-in-apa-style.html and in particular

> Of course, you may want to reference just one article within a special issue or special section. That’s okay! To do so, just use the journal article reference format, as usual. (You can find examples in this sample reference list.)

makes me think that it would be most appropriate to simply go with `number`, but then the problem is that one would put non-integer values there (which is actively discouraged).

**Comment by plk** [comment]
Ok, I have moved such cases to be periodicals, that's more sensible. For some reason I can't remember, periodical wasn't used at all.

**Comment by moewew** [comment]
Just to reiterate and for the benefit of the people coming here via their favourite search engine:
`number` is the most appropriate field here, `issue` gives sub-par results. There is an issue at the `biblatex` bugtracker (https://github.com/plk/biblatex/issues/726) that discusses changes to the documentation and data model to officially endorse using `number` instead of `issue` here.
