### ISSUE TITLE
Missing comma for two family-given names

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#48]
Via https://tex.stackexchange.com/q/417648/35864

Example `7.01:1` should come out as
> Herbst-Damm, K. L., & Kulik, J. A. (2005). ...

with `biblatex-apa` v7.5 it comes out as
> Herbst-Damm, K. L. & Kulik, J. A. (2005). ...

The comma before the "&" is missing. I had this checked with the printed APA manual, and http://blog.apastyle.org/apastyle/2017/03/how-to-create-references-when-words-in-the-title-are-italicized.html also suggests that there should be a comma before the "&" even if there are only two authors.

One cant simply change `finalnamedelim` since names in 'given family' order should follow the 'normal' rules for Oxford commas. Cf. `7.02:25` where "M. Eid & R. J. Larsen" without comma is correct.

```latex
\documentclass{article}
\usepackage[american]{babel}
\usepackage{csquotes}

\begin{filecontents*}{\jobname.bib} 
@ARTICLE{7.01:1,
  AUTHOR         = {K. L. Herbst-Damm and J. A. Kulik},
  TITLE          = {Volunteer Support, Marital Status, and the Survival Times of Terminally Ill Patients},
  JOURNALTITLE   = {Health Psychology},
  VOLUME         = {24},
  PAGES          = {225--229},
  DATE           = {2005},
  DOI            = {10.1037/0278-6133.24.2.225},
  URL            = {http://some.url},
}
@INBOOK{7.02:25,
  AUTHOR         = {D. M. Haybron},
  EDITOR         = {M. Eid and R. J. Larsen},
  TITLE          = {Philosophy and the Science of Subjective Well-Being},
  BOOKTITLE      = {The Science of Subjective Well-Being},
  LOCATION       = {New York, NY},
  PUBLISHER      = {Guildford Press},
  PAGES          = {17-43},
  DATE           = {2008},
}
\end{filecontents*}

\usepackage[backend=biber,style=apa]{biblatex}
\DeclareLanguageMapping{american}{american-apa}
\addbibresource{\jobname.bib} 

\begin{document}
  \textcite{7.01:1}
  \textcite{7.02:25}

  \parencite{7.01:1}
  \parencite{7.02:25}

  \printbibliography
\end{document}
```

I have an idea for a fix and could submit a pull request if you like.

**Comment by plk** [comment]
I need fo check some notes as I have a feeling that this is covered by some APA blog addendum.

**Comment by moewew** [comment]
In case it helps with your investigation, the following three recent blog posts also place a comma before the "&" in two-author citations: http://blog.apastyle.org/apastyle/2018/02/whats-in-a-name-authors-with-the-same-surname.html
> Green, L. [Leonard], & Myerson, J. (2013). ...

granted, that one might be thought of as special.

http://blog.apastyle.org/apastyle/2017/04/how-to-alphabetize-a-number.html
> Farthing, T., & Oates, P. P. (2010). ...

http://blog.apastyle.org/apastyle/2017/03/how-to-create-references-when-words-in-the-title-are-italicized.html
> Corballis, M. C., & McLaren, R. (1984). ...
> Lai, J., Fidler, F., & Cummings, G. (2015). ...

**Comment by plk** [comment]
Hmm, you're right. This used to work and somewhere along the way, the comma disappeared ...

**Comment by plk** [comment]
Very good, thanks. I can't even remember how all those explicit spaces/penalties were introduced. Nice to have them cleaned up. I diffed with the reference test doc and the only change with your patch is the correct commas. I will release with 2.11/3.11. Currently, the BSD biber builder will upload at the weekend and then we should be able to release everything.

**Comment by plk** [comment]
Yes, I'll add `sortcites`. There are certainly some artefacts in the APA style but I tend to leave it until someone finds a case I can add to the test suite to avoid breaking other things as it's so complex now, I can't remember why I did various things ...

**Comment by moewew** [comment]
OK. Regarding the `\ifuseprefix` thing you may want to have a look at the entry `presufftest` in `biblatex-apa-test.tex`. With `useprefix=true` (the default) we obtain
> A test of prefix 2. (1969). In P. L. von Greaves Jr. (Ed.). 

But with `useprefix=false` we get
> A test of prefix 2. (1969). In P. L. Greaves, Jr. (Ed.). 

The 'von' is gone, and there is no way to find out about it any more.

**Comment by plk** [comment]
True but since APA style mandates `useprefix=true`, I didn't really care about this ...

**Comment by moewew** [comment]
Fair enough. I'll prepare a pull request with my suggestion, then you can have a look and see if it worth merging. It should actually make the code shorter and it should not change the output with `useprefix=true`, but it should give better results with `useprefix=false`.
