### ISSUE TITLE
Location and publisher not omitted despite entry having doi

### ISSUE THREAD

**Issue by PsychicBirdy** [plk/biblatex-apa#54]
Consider
```
\documentclass[paper=a4]{article}
\usepackage[american]{babel}
\usepackage{csquotes}

\usepackage[style=apa]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
% (APA 7.04 Example 39)
@INPROCEEDINGS{7.04:39,
	AUTHOR         = {I. Katz and K. Gabayan and H. Aghajan},
	TITLE          = {A Multi-touch Surface Using Multiple Cameras},
	EDITOR         = {J. Blanc-Talon and W. Philips and D. Popescu and P. Scheunders},
	MAINTITLE      = {Lecture {N}otes in {C}omputer {S}cience},
	VOLUME         = {4678},
	BOOKTITLE      = {Advanced {C}oncepts for {I}ntelligent {V}ision {S}ystems},
	PAGES          = {97--108},
	LOCATION       = {Berlin, Germany},
	PUBLISHER      = {Springer-Verlag},
	DATE           = {2007},
	DOI            = {10.1007/978-3-540-74607-2_9}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{7.04:39}
\printbibliography
\end{document}
```
gives

> ... (pp. 97–108). Berlin, Germany: Springer-Verlag. doi:10.1007/978-3-540-74607-2_9

with biblatex-apa 7.6, biblatex 3.11 and biber 2.11. However, according to the APA Manual there shouldn't be a location and publisher mentioned when there is a doi. So this should actually give

> ... (pp. 97–108). doi:10.1007/978-3-540-74607-2_9

Tested with TeXlive 2018 pretest.

**Comment by plk** [comment]
Do you have a reference (APA blog for example) where this is stated? Currently, this is correct according to the example 7.04:39 on page 207 of the second printing 6th ed manual.

**Comment by PsychicBirdy** [comment]
My printing is 4th (paperback), April 2010. Please find an excerpt attacched. Everything stated in the excerpt can also be found in the 6th (paperback) printing, July 2012, and in the 6th (hardback) printing, November 2015. These seem to be corrections made after the 2nd printing.
[APA_excerpt.pdf](https://github.com/plk/biblatex-apa/files/1808654/APA_excerpt.pdf)

**Comment by plk** [comment]
Ok, will be fixed in next version.
