### ISSUE TITLE
Video entry erroneously has period following author

### ISSUE THREAD

**Issue by PsychicBirdy** [plk/biblatex-apa#55]
Consider
```
\documentclass[paper=a4]{article}
\usepackage[american]{babel}
\usepackage{csquotes}

\usepackage[style=apa]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
% (APA 7.07 Example 49)
% We render this with "retrieved from" instead of "available from" as this is arbitrary
% and ugly to parameterise. Forcing this means we can use a localisable string for "retrieved"
@VIDEO{7.07:49,
	ENTRYSUBTYPE   = {{DVD}},
	PRODUCER       = {{American Psychological Association}},
	TITLE          = {Responding Therapeutically to Patient Expressions of Sexual Attraction},
	DATE           = {2000},
	URL            = {http://www.apa.org/videos/}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{7.07:49}
\printbibliography
\end{document}
```
gives

> American Psychological Association. (Producer). ...

with biblatex-apa 7.6, biblatex 3.11 and biber 2.11. But according to the APA Manual it should give

> American Psychological Association (Producer). ...

Compare also to 7.07:53. Tested with TeXlive 2018 pretest.

**Comment by plk** [comment]
Which printing do you have of the manual? Mine has

> American Psychological Association. (Producer). ...

**Comment by PsychicBirdy** [comment]
My colleagues and mine printing are 4th (paperback) printing, April 2010; 6th (paperback) printing, July 2012; and 6th (hardback) printing, November 2015. See issue #54 for an excerpt.

**Comment by plk** [comment]
Fixed on master branch.
