### ISSUE TITLE
"Available from" or "Retrieved from"?

### ISSUE THREAD

**Issue by PsychicBirdy** [plk/biblatex-apa#56]
The comment in biblatex-apa-test-references.bib on example 7.07:49, that is,

> American Psychological Association (Producer). (2000). Responding therapeutically to patient expressions of sexual attraction [DVD]. Retrieved from http://www.apa.org/videos/

reads

> We render this with "retrieved from" instead of "available from" as this is arbitrary and ugly to parameterise. Forcing this means we can use a localisable string for "retrieved"

However, I'm not convinced by this argument. Consider you buy access to an online video via http://www.apa.org/videos/ - I think in this case "Retrieved from" would actually be fine. However, in the case of the source cited, it's a DVD. You do not retrieve a DVD from http://www.apa.org/videos/, you order it via this link. It's actually available via http://www.apa.org/videos/. Shouldn't there be the option to have "Available from" for such cases?

**Comment by plk** [comment]
Fair enough. It's a pain as this is a semantic difference, which the APA usually don't think about in terms of automation but it can be conditionalised on the subtype being a physical entity like "{DVD}".
