### ISSUE TITLE
Fixing reviews and peer commentaries (7.06)

### ISSUE THREAD

**Issue by PsychicBirdy** [plk/biblatex-apa#60]
The code for reviews and peer commentaries needs some fixing.

- The comment on 7.06:45 in biblatex-apa-test-references.bib states:
> % Note how this is handled by the biblatex/biber "related entries" functionality
> % We have included the year in the reviewed item for consistency, as per 7.06:46
> % The comma after the reviewed title is ommited for consistency, as per 7.06:48

Including the year is fine. But ommiting the comma for consistency turns things upside down. The model notation on p. 208 is:
> ... [Review of the book _Title of book,_ by A. A. Author]. ...

Also all the examples except for 48, that is 45 to 47, have the comma. Thus, for consistency the comma should be kept and added in 48.

- Just a minor issue: The APA manual has 7.06:48 wrong. The example there is

> Wolf, K. S. (2005). _The future for Deaf individuals is not that bleak_ [Peer commentary on the paper "Decrease of Deaf potential in a mainstreamed environment" by K. S. Wolf). Retrieved from http://www.personalityresearch.org/papers/hall.html#wolf

However, looking up that website, the original paper the comment is on is by W. C. Hall. Here is a fix for biblatex-apa-test-references.bib
```
@ARTICLE{deaf,
  AUTHOR         = {W. C. Hall},
  TITLE          = {``{D}ecrease of {D}eaf potential in a mainstreamed environment''},
  JOURNALTITLE   = {Some Journal},
  VOLUME         = {2},
  NUMBER         = {1},
  PAGES          = {1--10},
  DATE           = {2003},
}
```

- The comment on 7.06:46 in biblatex-apa-test-references.bib states:
% Note that this example drops the "produced" in the reviewed item. It's not worth
% automating this sort of verb as "by" is perfectly acceptable.

I don't agree. "produced by" is not redundant because it has a distinguishing function. For example, "BioShock" in example 47 is produced by 2K Games, whereas the games' authors are Ken Levine, Scott Sinclair and Paul Hellquist. Possibly, this can be added. The entry "apavid2" already uses the field "producer", the entry "bioshock" uses "author".

**Comment by plk** [comment]
Please try the 7th Edition Style which is now release (version 9.1 has just been pushed to CTAN). These strange formats have been comprehensively regularised by the APA and this issue has gone away I believe.
