### ISSUE TITLE
German APA, adding details for foreign language publications according to DGP

### ISSUE THREAD

**Issue by PsychicBirdy** [plk/biblatex-apa#61]
The latest manual from the DGP 4th ed. from 2016 (and also the former 3rd ed.) handles entries of foreign language publications a little different than the APA manual. Not only the year of the original publication is given (as in APA 7.02:21) but also title and/or author when these are not identical with the translated edition. Two examples are given, on p. 119 and p. 155:

> Lindsay, P. H. & Norman, D. A. (1981). _Einführung in die Psychologie_ (H.-D. Dumpert, F. Schmidt, M. Schuster & M. Steeger, Übers.). Berlin: Springer. (Original erschienen 1977: Human information processing)

> Zimbardo, P. G. & Gerrig, R. J. (2014). _Psychologie_ (20. Aufl.). München: Pearson Studium. (Original erschienen 2002 als Gerrig, R. J. & Zimbardo, P. G., Psychology and life)

I already attempted to rebuild these some time ago, see here: https://tex.stackexchange.com/questions/78247/german-apa-reference-origyear-field-is-incomplete-needs-reprinttitle

Here is a MWE:
```
\documentclass[paper=a4]{article}
\usepackage[american,ngerman]{babel}
\usepackage{csquotes}
\usepackage[style=apa]{biblatex}

\DeclareFieldFormat{origyear}{%
	\mkbibparens{\bibcpstring{origyear}~\thefield{origyear}%
		\ifnameundef{origauthor}
		{}
		{\addspace als \printnames[author]{origauthor}}%
		\iffieldundef{reprinttitle}
		{}%
		{\ifnameundef{origauthor}
			{\setunit{\addcolon\addspace}}
			{\setunit{\addcomma\addspace}}%
			\printfield{reprinttitle}}}%
}

\renewbibmacro*{origyear}{%
	\ifthenelse{
		\NOT\iffieldsequal{labelyear}{origdateyear}
		\OR
		\NOT\iffieldsequal{title}{reprinttitle}
		\OR
		\NOT\ifnamesequal{author}{origauthor}
	}
	{\printfield{origyear}}
	{}%
}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@BOOK{testentry1,
	author = {P. H. Lindsay and D. A. Norman},
	translator = {H.-D. Dumpert and F. Schmidt and M. Schuster and M. Steeger},
	title = {Introduction to psychology},
	subtitle = {Test subtitle},
	origtitle = {Einführung in die Psychologie},
	location = {Berlin},
	publisher = {Springer},
	date = {1981},
	origdate = {1977},
	origauthor = {P. H. Lindsay and D. A. Norman},
	titleaddon = {Test title addon},
	reprinttitle = {Human information processing},
}

@BOOK{testentry2,
	author = {P. G. Zimbardo and R. J. Gerrig},
	title = {Psychology},
	subtitle = {Test subtitle},
	origtitle = {Psychologie},
	edition = {20},
	location = {München},
	publisher = {Pearson Studium},
	date = {2014},
	origdate = {2002},
	origauthor = {R. J. Gerrig and P. G. Zimbardo},
	titleaddon = {Test title addon},
	reprinttitle = {Psychology and life},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
	\cite{testentry1}
	
	\cite{testentry2}
	\printbibliography
\end{document}
```

This doesn't work entirely anymore. Testentry 1 works fine, but testentry2 gives

> ... (Original erschienen 2002: Psychology and life)

when it should give

> ... (Original erschienen 2002 als Gerrig, R. J. & Zimbardo, P. G., Psychology and life)

**Comment by plk** [comment]
I would recommend creating a new biblatex style for the DGP, perhaps copied initially from the APA.  It is likely it will need more significant modifications over time which will be messy to deal with as macro modifications on top of the APA.
