### ISSUE TITLE
Handle multiple shortauthor

### ISSUE THREAD

**Issue by rstub** [plk/biblatex-apa#63]
Consider the following example:

```
\documentclass[american]{article}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[backend=biber, style=apa, sortcites]{biblatex}
\DeclareLanguageMapping{american}{american-apa}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Book{standards,
  title = {{Standards for Educational and Psychological Testing}},
  author = {{American Educational Research Association} and {American Psychological Association} and {National Council on Measurement in Education}},
  shortauthor = {{AERA} and {APA} and {NCME}},
  publisher = {American Educational Research Association},
  address = {Washington, DC},
  year = {2014}
}\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}        
\autocite{standards}

\autocite{standards}

\printbibliography
\end{document}
```

This renders as:

> (American Educational Research Association, American Psychological As-
> sociation, & National Council on Measurement in Education [AERA et al.],
> 2014)
> (AERA, 2014)

I would have expected

> (American Educational Research Association [AERA], American Psychological As-
> sociation [APA], & National Council on Measurement in Education [NCME],
> 2014)
> (AERA et al., 2014)

Or at least:

> (American Educational Research Association, American Psychological As-
> sociation, & National Council on Measurement in Education [AERA et al.],
> 2014)
> (AERA et al., 2014)

I am using

> 2017/01/06 v7.4 APA biblatex citation style

This issue is motivated by https://stackoverflow.com/questions/48303890/using-short-author-citations-in-bookdown-rmarkdown.

**Comment by moewew** [comment]
I have come to the conclusion that a combination of `author` and `shortauthor` is not really equipped to allow for a per-name abbreviation across several entries. With `author` and `shortauthor` one basically only has the choice to typeset the long form or the short form per name list. But we want a per-name decision. Theoretically it might be possible to loop over the `author` list and only extract the corresponding `shortauthor` value if necessary, but I could not find a simple way to do that: It either required nested calls to name formats which got out of hand quickly or it would require faking the `\printnames` loop "from the outside".

The best solution I could find so far used the extended name format and requires to input both the long and the short form of a corporate author along with a `nametemplates` marker: https://tex.stackexchange.com/q/449052/35864. This works well, but is a bit of a nightmare on the input side.

Things could be simplified if data annotations could hold more than just boolean values: Then one could use something like
```
author   = {{American Educational Research Association} and {American Psychological Association}
            and {National Council on Measurement in Education}},
author+an = {1:acro:={AERA}; 2:acro:={APA}; 3:acro:={NCME}},
```
@plk Would that be worth a consideration/feature request?

**Comment by plk** [comment]
Yes, this seems useful and natural extension of metadata annotations. I have implemented a "literal annotation" feature for this - see what you think. See 3.6.1 in the DEV biblatex manual. You'll also need to get the latest DEV biber.

**Comment by moewew** [comment]
I gave the example a short spin and the examples work well so far. There are two things that I noticed

1. Would it be possible to allow for several named literal annotations? I can imagine that it would help to be able to pass several string annotations (suppose I would like to use annotations for an author's date of birth and date of death but also for short acronyms, with only one default literal annotation that would be hard to pull of since I don't know which is which when I process a name).

2. Is there a test to check if the annotation contains anything?

Forth the record: I just realised that the annotation feature is probably not the best fit for the short acronym feature here. The huge advantage of the extended name format is that it can be used in `uniquename` features, it would be unreasonable to demand that field annotations could be used for that.

**Comment by plk** [comment]
Multiple, named annotations are now supported, please get the latest dev releases to test. For the test to check if the annotation contains anything, do you mean a test to see if any annotation exists at all for some piece of data?

**Comment by moewew** [comment]
@plk Thank you, I'll hopefully be able to have a more in-depth look at the new annotation features at the weekend or shortly after.

I was thinking of a test that could help avoid the empty pair of parentheses in
```
\documentclass[a4paper]{article}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@MISC{ann,
  author    = {{American Educational Research Association} and {American Psychological Association}
               and {National Council on Measurement in Education} and Anne Elk},
  author+an = {1:family="AERA"; 2:family="APA"; 3:family="NCME"},
  title     = {The Title},
}
\end{filecontents}
\usepackage[backend=biber, maxbibnames=999]{biblatex}
\addbibresource{\jobname.bib}


\renewcommand*{\mkbibnamefamily}[1]{%
  \ifpartannotation{family}{}{T}{F}%
  #1\space\mkbibparens{\getpartannotation{family}}}

\begin{document}
\cite{ann}
\printbibliography
\end{document}
```
`\ifpartannotation` does not work for that since the string annotation is essentially anonymous and not like the other annotations which work like boolean annotations that have a name and can essentially be queried as true (present)/false (absent) with `\ifpartannotation{family}{student}`. I'm not sure if `\haspartannotation` can help me here, but I haven't had a closer look. At first glance the output with
```
\renewcommand*{\mkbibnamefamily}[1]{%
  \haspartannotation{family}{}{TRUE }{FALSE }%
  #1\space\mkbibparens{\getpartannotation{family}}}
```
in the example seems weird if not wrong, I get
> FALSE American Educational Research Association (AERA), FALSE American Psychological Association (APA), FALSE National Council on Measurement in Education (NCME), and Anne **TRUE FALSE** Elk ().

**Comment by plk** [comment]
It's just a normal conditional:

```
\documentclass[a4paper]{article}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@MISC{ann,
  author    = {{American Educational Research Association} and {American Psychological Association}
               and {National Council on Measurement in Education} and Anne Elk},
  author+an = {1:family="AERA"; 2:family="APA"; 3:family="NCME"},
  title     = {The Title},
}
\end{filecontents}
\usepackage[backend=biber, maxbibnames=999]{biblatex}
\addbibresource{\jobname.bib}


\renewcommand*{\mkbibnamefamily}[1]{%
  \haspartannotation{family}
    {#1\space\mkbibparens{\getpartannotation{family}}}
    {#1}}

\begin{document}
\cite{ann}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
Aha, I got confused and thought there needed to be another argument. That explains the weird output. Thank you.

I'll have a look at the other issues I mentioned later.

**Comment by moewew** [comment]
I had a closer look at the new features and I think I can sort of get what I had in mind now. But there are a few things I noticed.

1. The interface with the name annotation feels awkward.
   - The multiple optional arguments mean that if I want to supply the annotation name I have to supply the other arguments as well
     ```
      \renewcommand*{\mkbibnamefamily}[1]{%
        #1%
        \haspartannotation[\currentname][acro][\the\value{listcount}]{family}
          {\addspace\mkbibparens{\getpartannotation[\currentname][acro][\the\value{listcount}]{family}}}
          {}}
      ```
      does not look very pretty
    - I have to admit that I don't have a good idea how things could be made to feel simpler. Especially since we want things to remain backwards compatible.
2. The field annotation do not follow `labelname` resolution. So
```
\documentclass[a4paper]{article}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@MISC{ann,
  author    = {{American Educational Research Association} and {American Psychological Association}
               and {National Council on Measurement in Education} and Anne Elk},
  author+an:acro = {1:family="AERA"; 2:family="APA"; 3:family="NCME"},
  title     = {The Title},
  date = {2018},
}
\end{filecontents}
\usepackage[backend=biber, style=authoryear, maxnames=999]{biblatex}
\addbibresource{\jobname.bib}


\renewcommand*{\mkbibnamefamily}[1]{%
  #1%
  \haspartannotation[\currentname][acro][\the\value{listcount}]{family}
    {\addspace\mkbibparens{\getpartannotation[\currentname][acro][\the\value{listcount}]{family}}}
    {}}

\begin{document}
\cite{ann}
\printbibliography
\end{document}
```
will only show the annotation in the bibliography (as `author`), but not in the citations (as `labelname`).

**Comment by plk** [comment]
Empty arguments are supported so you can just do:

```
\renewcommand*{\mkbibnamefamily}[1]{%
  #1%
  \haspartannotation[][acro]{family}
    {\addspace\mkbibparens{\getpartannotation[][acro]{family}}}
  {}}
```

and this seems to work. Using expclicit `\currentname` resolves to the actual name and bypassed `labelname`.

**Comment by moewew** [comment]
Oh, sorry, I should have thought about that ... That makes things much easier on the eye.

I'm wondering if it would be more intuitive to have `\has...annotation` only respond to string annotations. All other ("boolean") annotations can be requested with `\if...annotation{...}` already. After all `\has...annotation` and `\get...annotation` seem like natural partners, but in
```
\documentclass[a4paper]{article}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@MISC{ann,
  author    = {{American Educational Research Association} and {American Psychological Association}
               and {National Council on Measurement in Education} and Anne Elk},
  author+an = {1:family=student; 2:family=student},
  author+an:acro = {1:family="AERA"; 2:family="APA"; 3:family="NCME"},
  title     = {The Title},
  date = {2018},
}
\end{filecontents}
\usepackage[backend=biber, style=authoryear, maxnames=999]{biblatex}
\addbibresource{\jobname.bib}


\renewcommand*{\mkbibnamefamily}[1]{%
  #1%
  \haspartannotation{family}{T}{F}
  \getpartannotation{family}
  \haspartannotation[][acro]{family}
    {\addspace\mkbibparens{\getpartannotation[][acro]{family}}}
  {}}

\begin{document}
\cite{ann}
\printbibliography
\end{document}
```
`\getpartannotation{family}` does nothing.

**Comment by plk** [comment]
Is the `labelname` resolution still not working? I think it should. I changes the `\has*annotation` to only check literal annotations ... I was thinking about that too.

**Comment by plk** [comment]
Is there anything else we need to do here @moewew?
