### ISSUE TITLE
Documentation implies that sortcites=false, but this is no longer true

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex-apa#65]
Section 4.1 of the manual seems to imply that `sortcites=false`, but this is no longer true. The manual currently states:

> Please note that APA style does not have multiple citation lists sorted—they appear in the order cited. Since `\fullcitebib` is a citation command, the citations will not be sorted which might appear odd since this «citation» style looks like a references section excerpt. There is no way around this since the `sortcites` biblatex option is a package-level option. If you want to customise such a fake references section «citation», you should probably be using `\printbibliography` with a filter.

**Comment by plk** [comment]
Docs fixed for next version.
