### ISSUE TITLE
Reprint from article

### ISSUE THREAD

**Issue by drgibbon** [plk/biblatex-apa#69]
I'm using TeXLive 2018 (updated to the latest packages) with `biblatex-apa`, and I'm trying to reference a journal article reprint found in a book chapter. The best output I can get is:

> Wertheimer, M. (1935). Laws of organization in perceptual forms. In W. D. Ellis (Ed. & Trans.), _A source book of Gestalt psychology_ (pp. 71–88). London, England: Routledge & Kegan Paul. (Reprinted from _Untersuchungen zur lehre von Gestalt_, 301–350, by M. Wertheimer)

For some reason the "Reprinted from" part is ignoring the reprint reference's date, journaltitle, and volume. Here's the bib entry for the primary source:
```
@InBook{Wertheimer1935,
  author      = {Max Wertheimer},
  title       = {Laws of Organization in Perceptual Forms},
  booktitle   = {A source book of {Gestalt} psychology},
  date        = {1935},
  editor      = {Willis D. Ellis},
  translator  = {Willis D. Ellis},
  publisher   = {Routledge \& Kegan Paul},
  location    = {London, England},
  pages       = {71--88},
  related     = {wgestalt},
  relatedtype = {reprintfrom},
}
```
and the reprint entry:
```
@Article{wgestalt,
  author       = {Max Wertheimer},
  title        = {Untersuchungen zur Lehre von {Gestalt}},
  journaltitle = {Psychologische Forschung},
  date         = {1923},
  volume       = {4},
  pages        = {301--350},
}
```

**Comment by plk** [comment]
This should be fixed in the new 7th edition conformant release.
