### ISSUE TITLE
Space after ellipsis

### ISSUE THREAD

**Issue by fritz71** [plk/biblatex-apa#70]
If there are more than 7 editors, there is no space after the ellipsis. There is no example in "Publication
Manual of the American Psychological Association" (Sixth Edition, 2010) though. If there are more than 7 autors, there is indeed a space after the ellipsis. Information on editors should be treated like information on authors. Note the following MWE:
```
\begin{filecontents*}{\jobname.bib}
@INCOLLECTION{Reimann2005,
  author =       {Reimann, G.},
  title =        {Rechtliche Rahmenbedingungen},
  booktitle =    {Grundwissen für die berufsbezogene Eignungsbeurteilung nach DIN 33430},
  publisher =    {Pabst},
  date =         {2005},
  editor =       {Westhoff, K. and Hellfritsch, L. J. and Hornke, L. F. and Kubinger, K. D. and Lang, F. and
  Moosbrugger, H. and Püschel, A. and Reimann, G.},
  pages =        {17-24},
  location=      {Lengerich},
  edition =      {2},
}
\end{filecontents*}

\listfiles
\documentclass{scrartcl}

\usepackage[T1]{fontenc}
\usepackage[ngerman]{babel}

\usepackage[
  style=apa,
]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}

\cite{Reimann2005}

\printbibliography

\end{document}
```
see also (in german): https://www.texwelt.de/wissen/fragen/24005/leerzeichen-nach-auslassungspunkten

**Comment by moewew** [comment]
A pull request with a simple fix for this is at https://github.com/plk/biblatex-apa/pull/71
