### ISSUE TITLE
backref option enabled by default

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#72]
This came up in https://tex.stackexchange.com/q/471395/35864

`biblatex-apa` enables `backref` explicitly in

https://github.com/plk/biblatex-apa/blob/88754e811b2c85961cbf8c8fd61c4caba27cf60e/tex/latex/biblatex-apa/bbx/apa.bbx#L254

but then does not always use it. The backrefs are only shown if the option `apabackref` is activated

https://github.com/plk/biblatex-apa/blob/88754e811b2c85961cbf8c8fd61c4caba27cf60e/tex/latex/biblatex-apa/bbx/apa.bbx#L298-L309

https://github.com/plk/biblatex-apa/blob/88754e811b2c85961cbf8c8fd61c4caba27cf60e/tex/latex/biblatex-apa/bbx/apa.bbx#L2202-L2209

Unless I'm missing something and the backref information is used for other purposes as well, `apa.bbx` would not have to say `backref=true` and could delegate the decision about whether or not backrefs ought to be shown to the user via the standard option and could drop `apabackref`.

```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backref=false, apabackref=false, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
Agreed - I can't remember why it was done this way and I will revert to the standard system in v9.1.

**Comment by plk** [comment]
Should be fixed in 9.1 release.

**Comment by moewew** [comment]
Thank you very much. I'm wondering if I should port this to `biblatex-apa6`. One the one hand I really think `apabackref` is an oddity that confuses users rather than help them. On the other hand such a change in the interface may cause backwards compatibility issues. WDYT?

**Comment by plk** [comment]
Yes, I'm happy for that to happen if you have time - APA 6th was hacked and tweaked over many years and so the origins of that option are lost in history, I can't see a reason for it either.
