### ISSUE TITLE
Support for Galician

### ISSUE THREAD

**Issue by vitormiguez** [plk/biblatex-apa#75]
I'm providing the galician-apa.lbx file.

**Comment by vitormiguez** [comment]
\ProvidesFile{galician-apa.lbx}[2018/04/02\space v7.7\space APA biblatex localisation]
\InheritBibliographyExtras{galician}

\setcounter{smartand}{0} % Turn off "smart and" or ampersands will all be replaced

% (APA 6.22) The example abbreviations

\NewBibliographyString{revisededition}
\NewBibliographyString{typechair}
\NewBibliographyString{typechairs}
\NewBibliographyString{typevolume}
\NewBibliographyString{typevolumes}
\NewBibliographyString{typeseries}
\NewBibliographyString{typeseriess}
\NewBibliographyString{typevolseries}
\NewBibliographyString{typevolseriess}
\NewBibliographyString{on}
\NewBibliographyString{retrieved}
\NewBibliographyString{available}
\NewBibliographyString{from}
\NewBibliographyString{archivedat}
\NewBibliographyString{origyear}
\NewBibliographyString{reviewof}
\NewBibliographyString{producer}
\NewBibliographyString{execproducer}
\NewBibliographyString{director}
\NewBibliographyString{writer}
\NewBibliographyString{with}

\DeclareBibliographyStrings{%
  inherit          = {galician},
  inpress          = {{no prelo}{no prelo}},% remove when biblatex has it
  january          = {{xaneiro}{xaneiro}},
  february         = {{febreiro}{febreiro}},
  march            = {{marzo}{marzo}},
  april            = {{abril}{abril}},
  may              = {{maio}{maio}},
  june             = {{xu\~no}{xu\~no}},
  july             = {{xullo}{xullo}},
  august           = {{agosto}{agosto}},
  september        = {{setembro}{setembro}},
  october          = {{outubro}{outubro}},
  november         = {{novembro}{novembro}},
  december         = {{decembro}{decembro}},
  nodate           = {{s\adddot d\adddot}{s\adddot d\adddot}},
  mathesis         = {{tese\addabbrvspace de\addabbrvspace mestrado}{tese\addabbrvspace de\addabbrvspace mestrado}},
  phdthesis        = {{tese\addabbrvspace doutoral}{tese\addabbrvspace doutoral}},
  revisededition   = {{edici\'on\space revisada}{edici\'on\space revisada}},
  producer         = {{produtor}{produtor}},
  execproducer     = {{produtor executivo}{produtor executivo}},
  director         = {{director}{director}},
  writer           = {{escritor}{escritor}},
  with             = {{con}{con}},
  page             = {{p\'axina}{{}p\adddot}},
  pages            = {{p\'axinas}{{}pp\adddot}},
  on               = {{o}{o}},
  retrieved        = {{obtido}{obtido}},
  available        = {{dispo\~nible}{dispo\~nible}},
  from             = {{desde}{desde}},
  archivedat       = {{arquivado en}{arquivado en}},
  reviewof         = {{revisi\'on\space de}{revisi\'on\space de}},
  paragraph        = {{\P}{\P}},
  paragraphs       = {{\P\P}{\P\P}},
  origyear         = {{data\space orixinal\space de\space publicaci\'on}{data\space orixinal\space de\space publicaci\'on}},
  typechair        = {{coordinador}{coord\adddot}},
  typechairs       = {{coordinadores}{coords\adddot}},
  typevolume       = {{editor\space do\space volume}{ed\adddotspace vol\adddot}},
  typevolumes      = {{editores\space do\space volume}{eds\adddotspace vol\adddot}},
  typeseries       = {{editor\space da\space serie}{ed\adddotspace ser\adddot}},
  typeseriess      = {{editores\space da\space serie}{eds\adddotspace ser\adddot}},
  typevolseries    = {{editor\space da\space serie\space e\space do\space volume}{ed\adddotspace vol\space\&\space ser\adddot}},
  typevolseriess   = {{editores\space da\space serie\space e\space do\space volume}{eds\adddotspace vol\space\&\space ser\adddot}},
  annodomini       = {{d\adddot\space C\adddot}{d\adddot\space C\adddot}},
  beforechrist     = {{a\adddot\space C\adddot}{a\adddot\space C\adddot}},
}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (APA 7.10 Example 68) Drop end* when they are the same as *

% You must use \printdate to get here otherwise it will be ignored
\DeclareBibliographyExtras{%
  \def\urldatecomma{\addcomma\addspace}%
  \protected\def\mkbibdateapalong#1#2#3{%
    \iffieldundef{#1}%
      {}%
      {\iffieldbibstring{#1}{\biblcstring{\thefield{#1}}}{\thefield{#1}}}%
    \iffieldundef{#2}%
      {}%
      {\iffieldundef{#1}%
        {}%
        {\addcomma\addspace}%
       \mkbibmonth{\thefield{#2}}}%
    \iffieldundef{#3}%
      {}%
      {\iffieldundef{#2}%
        {}%
        {\addspace}%
       \stripzeros{\thefield{#3}}}}%
  \protected\def\mkbibdateapalongextra#1#2#3{%
    \iffieldundef{#1}%
      {}%
      {\iffieldbibstring{#1}{\biblcstring{\thefield{#1}}}{\thefield{#1}}\printfield{extradate}}%
    \iffieldundef{#2}%
      {}%
      {\iffieldundef{#1}%
        {}%
        {\addcomma\addspace}%
    \iffieldundef{#3}%
      {}%
      {\iffieldundef{#2}%
        {}%
        {\stripzeros{\thefield{#3}}\addspace de\addspace}}%
       \mkbibmonth{\thefield{#2}}%
}}%
  \protected\def\mkbibdateapalongmdy#1#2#3{%
    \iffieldundef{#3}%
      {}%
      {el\addspace\stripzeros{\thefield{#3}}}%
    \iffieldundef{#2}%
      {\addspace{en}\addspace}%
      {\iffieldundef{#3}%
        {en\addspace}%
        {\addspace{de}\addspace}%
       \mkbibmonth{\thefield{#2}}{\addspace{de}\addspace}}%
    \iffieldundef{#1}%
      {}%
      {\iffieldundef{#2}%
        {}%
        {\addspace}%
       \thefield{#1}}}}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\endinput

**Comment by vitormiguez** [comment]
[galician-apa.lbx.zip](https://github.com/plk/biblatex-apa/files/3691457/galician-apa.lbx.zip)

**Comment by plk** [comment]
I have added this to the DEV version and will push soon - can you let me know your full name so that I can add you to the Acknowledgements?

**Comment by vitormiguez** [comment]
My name is Vítor Míguez. Thank you!
