### ISSUE TITLE
request for a freeform type to replace the old literal in apacite

### ISSUE THREAD

**Issue by 2011** [plk/biblatex-apa#77]
Hi,

I discussed this with moewew (incorrectly in the general biblitex issues) here:

https://github.com/plk/biblatex/issues/884

Yes, I would like to see a freeform citation simply to get exactly the output I want in the cases that biblatex-apa doesn't handle (legal citations being one of the most common).

**Comment by plk** [comment]
I have just released version 9, conforming to the 7th edition. I plan to complete the style with the section 11 legal citations soon.

**Comment by plk** [comment]
9.1 has just been pushed to CTAN and includes coverage for all legal examples in section 11 of the APA 7th edition.
