### ISSUE TITLE
Space after nptextcite

### ISSUE THREAD

**Issue by adrianktng** [plk/biblatex-apa#79]
Would like to ask if it is intentional to leave a space after the nptext cite?
If yes, is it possible to go around it? (I know that we can add [⟨prenote⟩][⟨postnote⟩] onto the cite instead of using nptextcite but then just want to see the laternatives.)

Thank you.

![1](https://user-images.githubusercontent.com/21164473/64189149-a2d1ed00-ce6b-11e9-8423-b526126cbb8c.png)

``` tex
\documentclass{article}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage[style=apa,backend=biber]{biblatex}
\bibliography{references.bib}

\begin{filecontents}{\jobname.bib}
    @article{einstein,
        author = {Albert Einstein},
        title = {the true about tree},
        journaltitle = {Annalen der Physik},
        year = {1905},
        volume = {322},
        number = {10},
        pages = {891--921}
    }
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
    (Hallo world \nptextcite{einstein}).
    \printbibliography
\end{document}
```

**Comment by plk** [comment]
Hah, we just overlapped on fixing this - I have just release 7.9 with this fix.

**Comment by adrianktng** [comment]
Thank you both for responding promptly at the same time :)
