### ISSUE TITLE
Transition to APA 7th ed.: Retain 6th ed. styles for a bit?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#81]
I see you have done quite a lot of work to get 7th ed. `biblatex-apa` out. Given that some people may have started with 6th-ed. projects and may want to finish their work in 6th-ed. style (cf. https://apastyle.apa.org/Blog/transition-seventh-edition) would it be possible to distribute the old files in `biblatex-apa` on CTAN (under a different name like `apa-6th` or the like) for a transitional period (say until November next year)? If you would like a hand in maintaining the old style for that period I'd be more than happy to help.

**Comment by plk** [comment]
Yes, I can do that - I was planning to release a "legacy" package of the last 6th ed release soon.

**Comment by plk** [comment]
I've created a branch for 6th edition at the point of last update (v8.0). I suppose the files in there will need to be renamed with a "6" suffix - do you have any time to do that currently?  Then we can push a "biblatex-apa6" style to CTAN and I will mention it in the new v7 docs (9.1 will be ready soon).

**Comment by moewew** [comment]
I'm just trying to trace down a bug with `csquotes`, but I will have at renaming the files later.

**Comment by plk** [comment]
Many thanks - fighting with the messy APA legal formats currently.

**Comment by moewew** [comment]
Files renamed in https://github.com/moewew/biblatex-apa/commit/f7d221d883cad26dc0f7d8340b1e21bc1ae7d7fe for https://github.com/moewew/biblatex-apa/commits/apa6.

I ran a short test and I *think* I didn't break things completely, but I may have overlooked one or two details.

If you want to publish this as a separate package on CTAN it may be better to open a new GitHub repository for it instead of keeping it in a branch to run along here.

**Comment by plk** [comment]
Can you merge that into the "apa6" branch for now and I'll run some tests. Version 9.1 of the 7th ed style is ready to go and I mention the legacy package in the documentation for this.

**Comment by moewew** [comment]
PR at https://github.com/plk/biblatex-apa/pull/82

**Comment by plk** [comment]
biblatex-apa6 has been released to CTAN.

**Comment by PsychicBirdy** [comment]
Great work, the new biblatex-apa and the legacy version for backward compatibility. It is most appreciated! I hope you can keep the legacy version alive not just for a bit.
