### ISSUE TITLE
Duplicating editors in reference list

### ISSUE THREAD

**Issue by wrightas** [plk/biblatex-apa#86]
When citing an @incollection in biblatex-apa, I am getting the volume editor's(s') name(s) printed twice in the reference list. MWE:

```
%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode
%TC:incbib
\documentclass{article}
\usepackage{polyglossia} 
\setdefaultlanguage[variant=american]{english}
\usepackage{csquotes}
\usepackage[style=apa, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{mwe.bib}
@incollection{Turing1954,
    Author = {Turing, Alan},
    Booktitle = {The Essential {Turing}: Seminal Writings in Computing, Logic, Philosophy, Artificial Intelligence, and Artificial Life plus The Secrets of Enigma},
    Crossref = {Turing2004},
    Origdate = {1954},
    Pages = {576-595},
    Title = {Solvable and Unsolvable Problems},
}
@collection{Turing2004,
    Date = {2004},
    Editor = {Copeland, B. Jack},
    Location = {Oxford},
    Publisher = {Oxford Univeristy Press},
    Shorttitle = {The Essential {T}uring},
    Title = {The Essential {T}uring: Seminal Writings in Computing, Logic, Philosophy, Artificial Intelligence, and Artificial Life Plus the Secrets of Enigma},}
\end{filecontents}

\addbibresource{mwe.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
Biber 2.14; XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019); BibLaTeX 3.14; BibLateX-APA 9.2; and csquotes 5.2j. 

![image](https://user-images.githubusercontent.com/59089937/71257941-f83ee680-2302-11ea-9349-34386140be4c.png)

The editor information in parentheses needs to be removed for APA7: [apastyle.apa.org/instructional-aids/reference-guide.pdf](url)

See https://tex.stackexchange.com/questions/521117/biblatex-apa-duplicating-editors-in-reference-list

**Comment by plk** [comment]
Due to the regularisation of APA7, there is no need to use less common entrytypes like `@COLLECTION` and `@INCOLLECTION`. You'll note that the comprehensive examples file .bib that comes with the package doesn't contain any of these types (there was 1, by mistake in 9.2 but this is removed in 9.3).  If you do this, it's fine:

```
@inbook{Turing1954,
    Author = {Turing, Alan},
    Booktitle = {The Essential {Turing}: Seminal Writings in Computing, Logic, Philosophy, Artificial Intelligence, and Artificial Life plus The Secrets of Enigma},
    Crossref = {Turing2004},
    Origdate = {1954},
    Pages = {576-595},
    Title = {Solvable and Unsolvable Problems}
}
@book{Turing2004,
    Date = {2004},
    Editor = {Copeland, B. Jack},
    Location = {Oxford},
    Publisher = {Oxford Univeristy Press},
    Shorttitle = {The Essential {T}uring},
    Title = {The Essential {T}uring: Seminal Writings in Computing, Logic, Philosophy, Artificial Intelligence, and Artificial Life Plus the Secrets of Enigma}}

```

If you have no control over the .bib, simply create a sourcemap to change to `@BOOK/@INBOOK` dynamically. I will make this more explicit in the doc for 9.3.

**Comment by moewew** [comment]
Wouldn't it be better if `biblatex-apa` simply had a style-level sourcemap that maps `@inbook` to `@incollection` etc.? I think it is not a good idea to advise people to use the 'wrong' (seen from the standard `biblatex` data model) entry type: That can have negative impact on portability. One relative strength of `biblatex` compared to BibTeX is its relatively large set of supported entry types that is supported across the board of all styles and seems to cover the most important use cases.

**Comment by plk** [comment]
Yes, that will be done for 9.3, too fast on clicking send ...

**Comment by moewew** [comment]
Oh, good. That sounds much better.

In that case you could think about removing all mentions of `@collection`, `@incollection` (and all other superfluous types) in the `.bbx` completely and add a note about this in the docs (in case people want to customise something and wonder why using `@incollection` doesn't work).

Note that there are a few differences between the `@inbook` and `@incollection` drivers in `apa.bbx`. There is also one `\ifentrytype{incollection}`.

**Comment by plk** [comment]
All already done on my local repo, I will be pushing it and 9.3 soon.

**Comment by plk** [comment]
9.3 has been sent to CTAN with these changes.

**Comment by wrightas** [comment]
Thank you for your help on this (and on biblatex-apa in general!)
