### ISSUE TITLE
DefineBibliographyStrings unable to access string set with NewBibliographyString

### ISSUE THREAD

**Issue by johannesbottcher** [plk/biblatex-apa#9]
The following example is unable to access a string defined with `\NewBibliographyStrings` for redefinition.   
Feature, or bug? 
For further reference: [TeX.SX chat transcript](http://chat.stackexchange.com/transcript/message/21441300#21441300)

```latex
\documentclass{article}
\usepackage[american]{babel}
\usepackage[style=apa]{biblatex}
\DeclareLanguageMapping{american}{american-apa}
%\NewBibliographyString{retrieved}
%defined in american-apa.lbx and hence loaded at this point
%shoudln't that be available for definition below?
\DefineBibliographyStrings{american}{
retrieved={some string}
}
\addbibresource{biblatex-examples.bib}
\begin{document}
\fullcite{ctan}
\end{document}
```

**Comment by u-fischer** [comment]
Imho this is the documentated behaviour: the string is declared only for the language speciﬁed by the name of the lbx ﬁle.

**Comment by johannesbottcher** [comment]
@u-fischer  just pasting the part you quoted: 
>"When used in an lbx,the key is initialized only for the language speciﬁed by the name of the lbx ﬁle. The keys listed in § 4.9.2 are deﬁned by default."
