### ISSUE TITLE
Unexpected comma and prenote position in \textcite

### ISSUE THREAD

**Issue by moewew** [plk/biblatex-apa#90]
Consider the following MWE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\textcite[see][380]{sigfridsson}

\printbibliography
\end{document}
```

> see, Sigfridsson and Ryde (1998, p. 380)

The comma after "see" is unexpected given that `\prenotedelim` is `\addspace`.

The position of the "see" is also different from what the standard styles do, they would move the prenote into the parentheses

> Sigfridsson and Ryde (see 1998, p. 380)

---

My guess for the culprit is

https://github.com/plk/biblatex-apa/blob/5c2f03a6bb3ad81ca30b5a847fb320a004078f49/tex/latex/biblatex-apa/cbx/apa.cbx#L225

That `\setunit` may have to be guarded with a test to avoid it being called on the first citekey.

I can prepare a pull request (also for `apa6`, which has the same issues) if you confirm that the comma is unwanted and make a ruling on the position of the prenote (should it go before the `\textcite` or into the parentheses).

**Comment by moewew** [comment]
While we are at it: Do we need

https://github.com/plk/biblatex-apa/blob/409aef9c660c26cff5bfdd0bb7ccf8285bafae16/tex/latex/biblatex-apa/bbx/apa6.bbx#L85-L96

If those definitions are needed, I'd definitely go with `\newcommand` instead of `\gdef`, but I doubt those commands are documented and used, so they can probably go...

**Comment by plk** [comment]
I think they can go - `\gdef` is certainly not good and I don't think they are used or documented.

**Comment by moewew** [comment]
Good. PR with that coming up (and something similar to https://github.com/plk/biblatex-apa/commit/03063f187f4793b16872c28a98adcfa2e28f0c2d)
